"""Closed enums used by the deterministic sUAS domain."""

from enum import StrEnum


class Locale(StrEnum):
    EN = "en"
    ES_CO = "es-CO"


class WorkloadProfile(StrEnum):
    PRACTICE = "PRACTICE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class AircraftMode(StrEnum):
    READY = "READY"
    TRANSIT = "TRANSIT"
    SEARCH = "SEARCH"
    HOLD = "HOLD"
    RETURN_TO_BASE = "RETURN_TO_BASE"
    LOST_LINK_PROCEDURE = "LOST_LINK_PROCEDURE"
    RECOVERED = "RECOVERED"
    MISSION_FAILED = "MISSION_FAILED"


class LinkState(StrEnum):
    NOMINAL = "NOMINAL"
    DEGRADED = "DEGRADED"
    LOST = "LOST"


class SensorState(StrEnum):
    NOMINAL = "NOMINAL"
    OFFLINE = "OFFLINE"


class ContactEvidence(StrEnum):
    NONE = "NONE"
    DETECTED = "DETECTED"
    INSPECTABLE = "INSPECTABLE"


class ContactWorkflow(StrEnum):
    UNDETECTED = "UNDETECTED"
    DETECTED = "DETECTED"
    INSPECTED = "INSPECTED"
    CLASSIFIED = "CLASSIFIED"
    PRIORITIZED = "PRIORITIZED"
    REPORTED = "REPORTED"


class ContactClassification(StrEnum):
    ROUTINE = "routine"
    PRIORITY = "priority"
    UNCERTAIN = "uncertain"


class ContactPriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class AlertSeverity(StrEnum):
    ADVISORY = "ADVISORY"
    CRITICAL = "CRITICAL"
    FATAL = "FATAL"


class AlertKind(StrEnum):
    ENERGY_RESERVE = "ENERGY_RESERVE"
    ENERGY_CRITICAL = "ENERGY_CRITICAL"
    LINK_LOST = "LINK_LOST"
    SEPARATION_ADVISORY = "SEPARATION_ADVISORY"
    SEPARATION_CRITICAL = "SEPARATION_CRITICAL"
    RUNTIME_FAILURE = "RUNTIME_FAILURE"


class EventKind(StrEnum):
    SWARM_CHANGED = "SWARM_CHANGED"
    AIRCRAFT_MODE_CHANGED = "AIRCRAFT_MODE_CHANGED"
    ENERGY_THRESHOLD_CROSSED = "ENERGY_THRESHOLD_CROSSED"
    LINK_STATE_CHANGED = "LINK_STATE_CHANGED"
    LOST_LINK_PROCEDURE_STARTED = "LOST_LINK_PROCEDURE_STARTED"
    CONTACT_EVIDENCE_CHANGED = "CONTACT_EVIDENCE_CHANGED"
    CONTACT_WORKFLOW_CHANGED = "CONTACT_WORKFLOW_CHANGED"
    CONTACT_CORRECTED = "CONTACT_CORRECTED"
    COVERAGE_UPDATED = "COVERAGE_UPDATED"
    SEPARATION_ADVISORY_OPENED = "SEPARATION_ADVISORY_OPENED"
    SEPARATION_VIOLATION = "SEPARATION_VIOLATION"
    SEPARATION_ALERT_CLOSED = "SEPARATION_ALERT_CLOSED"
    CONFLICT_INJECTION_STARTED = "CONFLICT_INJECTION_STARTED"
    CONFLICT_INJECTION_SKIPPED = "CONFLICT_INJECTION_SKIPPED"
