const data=await fetch('../video/chapters.json').then(r=>r.json());
const $=s=>document.querySelector(s),video=$('#video');let current=0;const answered=new Set();
const clock=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
$('#duration').textContent=`${data.length} capítulos · ${clock(data.at(-1).end)} · OpenAI TTS HD · onyx`;
function show(i){current=i;const c=data[i];$('#stage').textContent=c.stage;$('#currentTitle').textContent=c.title;$('#transcript').textContent=c.text;$('#points').replaceChildren(...c.points.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));document.querySelectorAll('#chapters button').forEach((b,n)=>b.setAttribute('aria-current',String(n===i)));}
function jump(i){i=Math.max(0,Math.min(data.length-1,i));$('#checkpoint').hidden=true;video.currentTime=data[i].start+.05;show(i);video.play().catch(()=>{});}
data.forEach((c,i)=>{const b=document.createElement('button');b.innerHTML=`<small>${clock(c.start)} · ${c.stage}</small>`;b.append(document.createTextNode(c.title));b.onclick=()=>jump(i);$('#chapters').append(b);});
video.addEventListener('timeupdate',()=>{const i=data.findIndex(c=>video.currentTime>=c.start&&video.currentTime<c.end);if(i>=0&&i!==current)show(i);const c=data[current];if($('#interactive').checked&&c.question&&!answered.has(current)&&video.currentTime>=c.end-.45){answered.add(current);video.pause();$('#question').textContent=c.question;$('#answers').replaceChildren(...c.answers.map((t,n)=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>{$('#feedback').textContent=n===c.correct?'Correcto. '+c.answers[c.correct]+'.':'Revise este punto: '+c.answers[c.correct]+'.';};return b;}));$('#feedback').textContent='';$('#checkpoint').hidden=false;}});
$('#back').onclick=()=>jump(current-1);$('#next').onclick=()=>jump(current+1);$('#repeat').onclick=()=>{answered.delete(current);jump(current);};$('#continue').onclick=()=>{$('#checkpoint').hidden=true;video.play();};show(0);
$('#full').hidden=!document.fullscreenEnabled;
$('#full').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{});};
let restoreInteractive=null;
document.addEventListener('fullscreenchange',()=>{
 $('#full').textContent=document.fullscreenElement?'Salir de pantalla completa':'Pantalla completa';
 // A native video-only fullscreen cannot show the HTML questions.
 if(document.fullscreenElement===video){restoreInteractive=$('#interactive').checked;$('#interactive').checked=false;}
 else if(restoreInteractive!==null){$('#interactive').checked=restoreInteractive;restoreInteractive=null;}
});
try{const{createStation}=await import('./scene.js');const station=createStation($('#scene'));window.station=station;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let playing=!reduced;$('#motion').textContent=playing?'Pausar movimiento':'Iniciar movimiento';$('#motion').onclick=()=>{playing=!playing;station.setPlaying(playing);$('#motion').textContent=playing?'Pausar movimiento':'Iniciar movimiento';};$('#explode').oninput=e=>station.setExplode(Number(e.target.value));$('#reset').onclick=()=>{station.reset();playing=false;$('#motion').textContent='Iniciar movimiento';$('#explode').value='0';};const info={monitor:'Pantalla: presenta instrucciones, estímulos y resultados.',keyboard:'Teclado: respuestas discretas. El mouse permite selección y seguimiento.',controller:'Controlador: depende del perfil de OpenMATB o del simulador Liftoff.',sensor:'Sensor: requiere conexión física y revisión de calidad. No se adquirieron señales en este video.',aircraft:'Aeronave simulada: representa la supervisión sUAS, sin conexión a aeronaves reales.'};document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{station.focus(b.dataset.part);$('#partInfo').textContent=info[b.dataset.part];});window.addEventListener('pagehide',()=>station.dispose(),{once:true});}catch(e){$('#scene').textContent='La vista 3D requiere WebGL 2. El video y los capítulos siguen disponibles.';console.error(e);}
