#!/usr/bin/env python3
"""
Copy military aviation assets (questionnaires + scenarios) into an OpenMATB tree.

Usage:
    python3 install_to_openmatb.py /custom/path
    OPENMATB_DIR=/custom/path python3 install_to_openmatb.py
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path

from matb_integration.communications_profile import (
    CommunicationsProfileError,
    verify_communications_audio_profile,
)

MATB_ROOT = Path(__file__).resolve().parent
QUESTIONNAIRES_SRC = MATB_ROOT / "matb_integration" / "questionnaires"
SCENARIOS_SRC = MATB_ROOT / "scenarios" / "military_aviation"

# Scenario manifests and scientific claims generated by this repository rely
# on these runtime extensions.  Merely finding an ``includes/`` directory is
# not evidence that an arbitrary OpenMATB checkout implements them.
REQUIRED_RUNTIME_CAPABILITIES: dict[str, str] = {
    "main.py": "Scheduler",
    "core/scenarioprovenance.py": "ScenarioProvenance",
    "core/scheduler.py": "ExperimentClock",
    "core/logger.py": "timing_qc_schema_version",
    "plugins/sysmon.py": "nontargetduration",
    "plugins/communications.py": "maxresponsedelay",
}


class IncompatibleOpenMATBError(RuntimeError):
    """Selected runtime does not implement the qualified MATB contract."""


def _default_openmatb() -> Path | None:
    raw = os.environ.get("OPENMATB_DIR")
    return Path(raw).expanduser() if raw else None


def verify_openmatb_runtime(openmatb_path: Path) -> dict[str, object]:
    runtime_root = openmatb_path.expanduser().resolve()
    includes = runtime_root / "includes"
    missing: list[str] = []
    for relative, marker in REQUIRED_RUNTIME_CAPABILITIES.items():
        path = runtime_root / relative
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            missing.append(f"{relative} (missing/unreadable)")
            continue
        if marker not in text:
            missing.append(f"{relative} (missing marker {marker!r})")
    if not includes.is_dir():
        missing.append("includes/ (missing directory)")
    if missing:
        raise IncompatibleOpenMATBError(
            "selected OpenMATB runtime lacks required scientific capability: "
            + "; ".join(missing)
        )
    try:
        communications_profile = verify_communications_audio_profile(
            runtime_root=runtime_root
        )
    except CommunicationsProfileError as exc:
        raise IncompatibleOpenMATBError(str(exc)) from exc
    return {
        "runtime_root": str(runtime_root),
        "capabilities": sorted(REQUIRED_RUNTIME_CAPABILITIES),
        "communications_profile": communications_profile,
    }


def install(openmatb_path: Path) -> None:
    qualification = verify_openmatb_runtime(openmatb_path)
    openmatb_path = Path(str(qualification["runtime_root"]))
    includes = openmatb_path / "includes"

    # Questionnaires
    q_dest = includes / "questionnaires"
    q_dest.mkdir(parents=True, exist_ok=True)
    for src in sorted(QUESTIONNAIRES_SRC.glob("*.txt")):
        dst = q_dest / src.name
        shutil.copy2(src, dst)
        print(f"  questionnaire: {src.name} → {dst}")

    # Scenarios
    s_dest = includes / "scenarios" / "military_aviation"
    s_dest.mkdir(parents=True, exist_ok=True)
    scenario_assets = [
        src for src in SCENARIOS_SRC.iterdir()
        if src.is_file() and (src.name.endswith(".txt") or src.name.endswith(".txt.manifest.json"))
    ]
    for src in sorted(scenario_assets):
        dst = s_dest / src.name
        shutil.copy2(src, dst)
        label = "manifest" if src.name.endswith(".manifest.json") else "scenario"
        print(f"  {label:<13} {src.name} → {dst}")

    print(f"\nDone. To run a scenario:")
    print(f"  cd {openmatb_path}")
    print(f"  DISPLAY=:100 python main.py   # Linux/headless")
    print(f"  python main.py                 # Windows / macOS")
    print(f"  # then select: scenarios/military_aviation/low_workload.txt")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Install military aviation assets into OpenMATB.")
    parser.add_argument(
        "openmatb_path",
        type=Path,
        nargs="?",
        default=_default_openmatb(),
        help="Path to an external OpenMATB directory, or set OPENMATB_DIR",
    )
    args = parser.parse_args()
    if args.openmatb_path is None:
        parser.error(
            "openmatb_path is required. Pass the tracked ./openmatb runtime, "
            "another compatible checkout, or set OPENMATB_DIR."
        )
    try:
        install(args.openmatb_path)
    except IncompatibleOpenMATBError as exc:
        parser.error(str(exc))
