"use client";

import React, { useState } from "react";
import type { AircraftSnapshot, CommandKind, ContactSnapshot, Locale, WorldSnapshot } from "@/types/simulation";
import { t } from "@/lib/simulation/i18n";
import { validCommandsFor } from "@/lib/simulation/store";
import { Button } from "@/components/ui/button";

interface CommandBarProps { snapshot: WorldSnapshot | null; selectedAircraft: AircraftSnapshot | null; selectedContact: ContactSnapshot | null; locale: Locale; readOnly?: boolean; pending?: boolean; onCommand: (kind: CommandKind, payload: Record<string, unknown>) => void; }
export function CommandBar({ snapshot, selectedAircraft, selectedContact, locale, readOnly = false, pending = false, onCommand }: CommandBarProps) {
  const [confirmReturn, setConfirmReturn] = useState(false);
  const aircraftKinds = validCommandsFor(selectedAircraft);
  const contactKinds = validCommandsFor(selectedContact);
  const command = (kind: CommandKind, payload: Record<string, unknown>) => { onCommand(kind, payload); setConfirmReturn(false); };
  const sectorId = Object.keys(snapshot?.sectors ?? {}).sort()[0];
  return <footer className="mission-panel rounded-none border-x-0 border-b-0 px-4 py-3"><div className="flex flex-wrap items-center gap-2"><span className="page-kicker mr-2">Command</span>{selectedAircraft ? <><span className="font-mono text-xs text-foreground">{selectedAircraft.aircraft_id}</span>{aircraftKinds.includes("ASSIGN_SECTOR") && sectorId && <Button type="button" size="sm" variant="outline" disabled={readOnly || pending} onClick={() => command("ASSIGN_SECTOR", { aircraft_id: selectedAircraft.aircraft_id, sector_id: sectorId })}>{t(locale, "command.assign_sector")}</Button>}{aircraftKinds.includes("HOLD") && <Button type="button" size="sm" variant="outline" disabled={readOnly || pending} onClick={() => command("HOLD", { aircraft_id: selectedAircraft.aircraft_id })}>{t(locale, "command.hold")}</Button>}{aircraftKinds.includes("RESUME_MISSION") && <Button type="button" size="sm" variant="outline" disabled={readOnly || pending} onClick={() => command("RESUME_MISSION", { aircraft_id: selectedAircraft.aircraft_id })}>{t(locale, "command.resume_mission")}</Button>}{aircraftKinds.includes("RETURN_TO_BASE") && (confirmReturn ? <><Button type="button" size="sm" variant="destructive" disabled={readOnly || pending} aria-label="Confirm return" onClick={() => command("RETURN_TO_BASE", { aircraft_id: selectedAircraft.aircraft_id })}>Confirm return</Button><Button type="button" size="sm" variant="ghost" onClick={() => setConfirmReturn(false)}>×</Button></> : <Button type="button" size="sm" variant="warning" disabled={readOnly || pending} onClick={() => setConfirmReturn(true)}>{t(locale, "command.return_to_base")}</Button>)}</> : selectedContact ? <><span className="font-mono text-xs text-foreground">{selectedContact.contact_id}</span>{contactKinds.map((kind) => <Button key={kind} type="button" size="sm" variant="outline" disabled={readOnly || pending} onClick={() => command(kind, { contact_id: selectedContact.contact_id, ...(kind === "CLASSIFY_CONTACT" ? { classification: "uncertain" } : kind === "SET_CONTACT_PRIORITY" ? { priority: "MEDIUM" } : kind === "REPORT_CONTACT" ? { note_code: "GENERAL" } : {}) })}>{t(locale, `command.${kind.toLowerCase()}` as never)}</Button>)}</> : <span className="text-sm text-muted-foreground">Select an aircraft or contact to issue a command.</span>}{pending && <span role="status" className="ml-auto font-mono text-[10px] uppercase text-warning">{t(locale, "command.pending")}</span>}</div></footer>;
}
