"use client";

import React from "react";
import type { ContactSnapshot, Locale } from "@/types/simulation";
import { t } from "@/lib/simulation/i18n";
import { Button } from "@/components/ui/button";

interface ContactQueueProps { contacts: ContactSnapshot[]; locale: Locale; onAction: (kind: "INSPECT_CONTACT" | "CLASSIFY_CONTACT" | "SET_CONTACT_PRIORITY" | "REPORT_CONTACT", contact: ContactSnapshot) => void; readOnly?: boolean; }
const workflowRank: Record<ContactSnapshot["workflow"], number> = { DETECTED: 0, INSPECTED: 1, CLASSIFIED: 2, PRIORITIZED: 3, REPORTED: 4, UNDETECTED: 9 };
export function sortContacts(contacts: ContactSnapshot[]) { return [...contacts].filter((contact) => contact.evidence !== "NONE").sort((left, right) => workflowRank[left.workflow] - workflowRank[right.workflow] || left.contact_id.localeCompare(right.contact_id)); }
export function ContactQueue({ contacts, locale, onAction, readOnly = false }: ContactQueueProps) {
  return <section aria-labelledby="mission-contact-heading" className="flex min-h-0 flex-1 flex-col"><div className="border-b border-white/10 px-4 py-3"><div className="page-kicker">{t(locale, "mission.evidence")} / {contacts.filter((contact) => contact.evidence !== "NONE").length.toString().padStart(2, "0")}</div><h2 id="mission-contact-heading" className="mt-1 font-display text-lg uppercase tracking-wide">{t(locale, "mission.contacts")}</h2></div><ol className="min-h-0 flex-1 space-y-2 overflow-y-auto p-3">{sortContacts(contacts).map((contact) => { const inspectable = contact.evidence === "INSPECTABLE" && ["DETECTED", "INSPECTED"].includes(contact.workflow); const needsClass = ["INSPECTED", "CLASSIFIED", "PRIORITIZED", "REPORTED"].includes(contact.workflow); const needsPriority = ["CLASSIFIED", "PRIORITIZED", "REPORTED"].includes(contact.workflow); const canReport = ["PRIORITIZED", "REPORTED"].includes(contact.workflow) && Boolean(contact.classification && contact.priority); return <li key={contact.contact_id} className="rounded border border-white/10 bg-black/15 p-3"><div className="flex items-center justify-between"><span className="font-mono text-sm font-semibold">{contact.contact_id}</span><span className="font-mono text-[10px] uppercase text-warning">{t(locale, `contact.workflow_${contact.workflow.toLowerCase()}` as never)}</span></div><div className="mt-2 flex flex-wrap gap-1">{inspectable && <Button type="button" size="sm" variant="outline" disabled={readOnly} onClick={() => onAction("INSPECT_CONTACT", contact)}>{t(locale, "contact.inspect", { contact: contact.contact_id })}</Button>}{needsClass && <Button type="button" size="sm" variant="outline" disabled={readOnly} onClick={() => onAction("CLASSIFY_CONTACT", contact)}>{t(locale, "command.classify_contact")}</Button>}{needsPriority && <Button type="button" size="sm" variant="outline" disabled={readOnly} onClick={() => onAction("SET_CONTACT_PRIORITY", contact)}>{t(locale, "command.set_contact_priority")}</Button>}{canReport && <Button type="button" size="sm" variant="outline" disabled={readOnly} onClick={() => onAction("REPORT_CONTACT", contact)}>{t(locale, "contact.report", { contact: contact.contact_id })}</Button>}</div></li>; })}</ol></section>;
}
