import { z } from "zod";
export type WattHours = number & { readonly __unit: "Wh" };
export type NauticalMiles = number & { readonly __unit: "NM" };
const id = z.string().trim().min(1);
const utc = z.string().regex(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,3}))?Z$/).refine((v) => { const m = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,3}))?Z$/.exec(v); if (!m) return false; const d = new Date(v); return Number.isFinite(d.getTime()) && d.getUTCFullYear() === +m[1] && d.getUTCMonth() + 1 === +m[2] && d.getUTCDate() === +m[3] && d.getUTCHours() === +m[4] && d.getUTCMinutes() === +m[5] && d.getUTCSeconds() === +m[6]; });
const pct = z.number().finite().min(0).max(100);
export type Joules = number & { readonly __unit: "J" }; export type Meters = number & { readonly __unit: "m" }; export type Seconds = number & { readonly __unit: "s" }; export type MetersPerSecond = number & { readonly __unit: "m/s" }; export type Watts = number & { readonly __unit: "W" };
export const nauticalMilesToMeters = (value: number): Meters => (value * 1852) as Meters;
export const feetToMeters = (value: number): Meters => (value * 0.3048) as Meters;
export const knotsToMetersPerSecond = (value: number): MetersPerSecond => (value * 0.5144444444444445) as MetersPerSecond;
export const wattHoursToJoules = (value: number): Joules => (value * 3600) as Joules;
export interface BatteryState { serialNumber: string; aircraftCompatibility: readonly string[]; chemistry: string; nominalCapacityWh: WattHours; nominalEnergyJ: Joules; cycles: number; ageDays: number; stateOfChargePercent: number; stateOfHealthPercent: number; cellImbalanceMv?: number; internalResistanceMohm?: number; temperatureC?: number; status: "released" | "restricted" | "quarantined"; rawTelemetryValues?: Record<string, string | number | boolean> }
export interface EnergySegment { id: string; kind: "climb" | "cruise" | "work" | "hold" | "return" | "diversion" | "contingency"; distanceNm: NauticalMiles; distanceM: Meters; durationS: Seconds; durationMinutes?: number; altitudeChangeFt?: number; altitudeChangeM?: Meters; expectedGroundspeedKt?: number; expectedGroundspeedMps?: MetersPerSecond; payloadPowerW?: Watts }
export interface ReservePolicy { recoveryMinimumPercent: number; diversionMinimumPercent: number; contingencyMinimumPercent: number; uncertaintyMethod: "approved-model"; effectiveFromUtc: string }
const raw = z.record(z.union([z.string(), z.number().finite(), z.boolean()]));
const BatterySchema = z.object({ serialNumber: z.string().regex(/^[A-Z0-9][A-Z0-9._-]{2,63}$/), aircraftCompatibility: z.array(id).min(1), chemistry: id, nominalCapacityWh: z.number().finite().positive().transform((v) => v as WattHours), nominalEnergyJ: z.number().finite().positive().transform((v) => v as Joules), cycles: z.number().int().nonnegative(), ageDays: z.number().finite().nonnegative(), stateOfChargePercent: pct, stateOfHealthPercent: pct, cellImbalanceMv: z.number().finite().nonnegative().optional(), internalResistanceMohm: z.number().finite().nonnegative().optional(), temperatureC: z.number().finite().optional(), status: z.enum(["released", "restricted", "quarantined"]), rawTelemetryValues: raw.optional() }).strict().superRefine((v, ctx) => { if (Math.abs(v.nominalEnergyJ - v.nominalCapacityWh * 3600) > 1e-6 * Math.max(1, v.nominalEnergyJ)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["nominalEnergyJ"], message: "normalized joules must match watt-hours" }); });
const SegmentSchema = z.object({ id, kind: z.enum(["climb", "cruise", "work", "hold", "return", "diversion", "contingency"]), distanceNm: z.number().finite().nonnegative().transform((v) => v as NauticalMiles), distanceM: z.number().finite().nonnegative().transform((v) => v as Meters), durationS: z.number().finite().nonnegative().transform((v) => v as Seconds), durationMinutes: z.number().finite().nonnegative().optional(), altitudeChangeFt: z.number().finite().optional(), altitudeChangeM: z.number().finite().transform((v) => v as Meters).optional(), expectedGroundspeedKt: z.number().finite().positive().optional(), expectedGroundspeedMps: z.number().finite().positive().transform((v) => v as MetersPerSecond).optional(), payloadPowerW: z.number().finite().nonnegative().transform((v) => v as Watts).optional() }).strict().superRefine((v, ctx) => { if (Math.abs(v.distanceM - v.distanceNm * 1852) > 1e-6 * Math.max(1, v.distanceM)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["distanceM"], message: "normalized meters must match nautical miles" }); if (v.durationMinutes !== undefined && Math.abs(v.durationS - v.durationMinutes * 60) > 1e-6 * Math.max(1, v.durationS)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["durationS"], message: "normalized seconds must match minutes" }); });
const ReserveSchema = z.object({ recoveryMinimumPercent: pct, diversionMinimumPercent: pct, contingencyMinimumPercent: pct, uncertaintyMethod: z.literal("approved-model"), effectiveFromUtc: utc }).strict();
export function parseBattery(value: unknown): BatteryState { return BatterySchema.parse(value); }
export function parseEnergySegment(value: unknown): EnergySegment { return SegmentSchema.parse(value); }
export function parseReservePolicy(value: unknown): ReservePolicy { return ReserveSchema.parse(value); }
