import { z } from "zod";
export type WattHours = number & { readonly __unit: "Wh" };
export type NauticalMiles = number & { readonly __unit: "NM" };
const id = z.string().trim().min(1);
const utc = z.string().regex(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,3}))?Z$/).refine((v) => { const m = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,3}))?Z$/.exec(v); if (!m) return false; const d = new Date(v); return Number.isFinite(d.getTime()) && d.getUTCFullYear() === +m[1] && d.getUTCMonth() + 1 === +m[2] && d.getUTCDate() === +m[3] && d.getUTCHours() === +m[4] && d.getUTCMinutes() === +m[5] && d.getUTCSeconds() === +m[6]; });
const pct = z.number().finite().min(0).max(100);
export type Joules = number & { readonly __unit: "J" }; export type Meters = number & { readonly __unit: "m" }; export type Seconds = number & { readonly __unit: "s" }; export type MetersPerSecond = number & { readonly __unit: "m/s" }; export type Watts = number & { readonly __unit: "W" };
const nonnegative = (value: number, name: string): number => { if (!Number.isFinite(value) || value < 0) throw new RangeError(`${name} must be finite and non-negative`); return value; };
export const nauticalMilesToMeters = (value: number): Meters => (nonnegative(value, "nautical miles") * 1852) as Meters;
export const feetToMeters = (value: number): Meters => (nonnegative(value, "feet") * 0.3048) as Meters;
export const altitudeChangeFeetToMeters = (value: number): Meters => { if (!Number.isFinite(value)) throw new RangeError("altitude change must be finite"); return (value * 0.3048) as Meters; };
export const knotsToMetersPerSecond = (value: number): MetersPerSecond => (nonnegative(value, "knots") * 0.5144444444444445) as MetersPerSecond;
export const wattHoursToJoules = (value: number): Joules => (nonnegative(value, "watt-hours") * 3600) as Joules;
export interface BatteryState { serialNumber: string; aircraftCompatibility: readonly string[]; chemistry: string; nominalCapacityWh: WattHours; nominalEnergyJ: Joules; cycles: number; ageDays: number; stateOfChargePercent: number; stateOfHealthPercent: number; cellImbalanceMv?: number; cellImbalanceV?: number & { readonly __unit: "V" }; internalResistanceMohm?: number; internalResistanceOhm?: number & { readonly __unit: "Ohm" }; temperatureC?: number; temperatureK?: number & { readonly __unit: "K" }; status: "released" | "restricted" | "quarantined"; rawTelemetryValues?: Record<string, string | number | boolean> }
export interface EnergySegment { id: string; kind: "climb" | "cruise" | "work" | "hold" | "return" | "diversion" | "contingency"; distanceNm: NauticalMiles; distanceM: Meters; durationS: Seconds; durationMinutes?: number; altitudeChangeFt?: number; altitudeChangeM?: Meters; expectedGroundspeedKt?: number; expectedGroundspeedMps?: MetersPerSecond; payloadPowerW?: Watts }
export interface ReservePolicy { recoveryMinimumPercent: number; diversionMinimumPercent: number; contingencyMinimumPercent: number; uncertaintyMethod: "approved-model"; effectiveFromUtc: string }
const raw = z.record(z.union([z.string(), z.number().finite(), z.boolean()]));
const BatterySchema = z.object({ serialNumber: z.string().regex(/^[A-Z0-9][A-Z0-9._-]{2,63}$/), aircraftCompatibility: z.array(id).min(1), chemistry: id, nominalCapacityWh: z.number().finite().positive().transform((v) => v as WattHours), nominalEnergyJ: z.number().finite().positive().transform((v) => v as Joules), cycles: z.number().int().nonnegative(), ageDays: z.number().finite().nonnegative(), stateOfChargePercent: pct, stateOfHealthPercent: pct, cellImbalanceMv: z.number().finite().nonnegative().optional(), cellImbalanceV: z.number().finite().nonnegative().transform((v) => v as BatteryState["cellImbalanceV"]).optional(), internalResistanceMohm: z.number().finite().nonnegative().optional(), internalResistanceOhm: z.number().finite().nonnegative().transform((v) => v as BatteryState["internalResistanceOhm"]).optional(), temperatureC: z.number().finite().optional(), temperatureK: z.number().finite().positive().transform((v) => v as BatteryState["temperatureK"]).optional(), status: z.enum(["released", "restricted", "quarantined"]), rawTelemetryValues: raw.optional() }).strict().superRefine((v, ctx) => { if (Math.abs(v.nominalEnergyJ - v.nominalCapacityWh * 3600) > 1e-6 * Math.max(1, v.nominalEnergyJ)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["nominalEnergyJ"], message: "normalized joules must match watt-hours" }); if ((v.cellImbalanceMv === undefined) !== (v.cellImbalanceV === undefined)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["cellImbalanceV"], message: "cell imbalance mV and V must be provided together" }); else if (v.cellImbalanceMv !== undefined && Math.abs(v.cellImbalanceV! - v.cellImbalanceMv / 1000) > 1e-9) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["cellImbalanceV"], message: "cell imbalance V must match mV" }); if ((v.internalResistanceMohm === undefined) !== (v.internalResistanceOhm === undefined)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["internalResistanceOhm"], message: "resistance mOhm and Ohm must be provided together" }); else if (v.internalResistanceMohm !== undefined && Math.abs(v.internalResistanceOhm! - v.internalResistanceMohm / 1000) > 1e-12) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["internalResistanceOhm"], message: "resistance Ohm must match mOhm" }); if ((v.temperatureC === undefined) !== (v.temperatureK === undefined)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["temperatureK"], message: "temperature C and K must be provided together" }); else if (v.temperatureC !== undefined && Math.abs(v.temperatureK! - (v.temperatureC + 273.15)) > 1e-9) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["temperatureK"], message: "temperature K must match C" }); });
const SegmentSchema = z.object({ id, kind: z.enum(["climb", "cruise", "work", "hold", "return", "diversion", "contingency"]), distanceNm: z.number().finite().nonnegative().transform((v) => v as NauticalMiles), distanceM: z.number().finite().nonnegative().transform((v) => v as Meters), durationS: z.number().finite().nonnegative().transform((v) => v as Seconds), durationMinutes: z.number().finite().nonnegative().optional(), altitudeChangeFt: z.number().finite().optional(), altitudeChangeM: z.number().finite().transform((v) => v as Meters).optional(), expectedGroundspeedKt: z.number().finite().positive().optional(), expectedGroundspeedMps: z.number().finite().positive().transform((v) => v as MetersPerSecond).optional(), payloadPowerW: z.number().finite().nonnegative().transform((v) => v as Watts).optional() }).strict().superRefine((v, ctx) => { if (Math.abs(v.distanceM - v.distanceNm * 1852) > 1e-6 * Math.max(1, v.distanceM)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["distanceM"], message: "normalized meters must match nautical miles" }); if (v.durationMinutes !== undefined && Math.abs(v.durationS - v.durationMinutes * 60) > 1e-6 * Math.max(1, v.durationS)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["durationS"], message: "normalized seconds must match minutes" }); if ((v.altitudeChangeFt === undefined) !== (v.altitudeChangeM === undefined)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["altitudeChangeM"], message: "altitude feet and meters must be provided together" }); else if (v.altitudeChangeFt !== undefined && Math.abs(v.altitudeChangeM! - v.altitudeChangeFt * 0.3048) > 1e-6 * Math.max(1, Math.abs(v.altitudeChangeM!))) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["altitudeChangeM"], message: "altitude meters must match feet" }); if ((v.expectedGroundspeedKt === undefined) !== (v.expectedGroundspeedMps === undefined)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["expectedGroundspeedMps"], message: "groundspeed knots and m/s must be provided together" }); else if (v.expectedGroundspeedKt !== undefined && Math.abs(v.expectedGroundspeedMps! - v.expectedGroundspeedKt * 0.5144444444444445) > 1e-6 * Math.max(1, v.expectedGroundspeedMps!)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["expectedGroundspeedMps"], message: "groundspeed m/s must match knots" }); });
const ReserveSchema = z.object({ recoveryMinimumPercent: pct, diversionMinimumPercent: pct, contingencyMinimumPercent: pct, uncertaintyMethod: z.literal("approved-model"), effectiveFromUtc: utc }).strict();
export function parseBattery(value: unknown): BatteryState { return BatterySchema.parse(value); }
export function parseEnergySegment(value: unknown): EnergySegment { return SegmentSchema.parse(value); }
export function parseReservePolicy(value: unknown): ReservePolicy { return ReserveSchema.parse(value); }
