"use client";

import { ScientificChart } from "@/components/charts/EChart";
import { buildDepdfCurveOption, buildDepdfParamOption } from "@/lib/figures";
import type { FitRow } from "@/types";
import { useAppLocale } from "@/lib/i18n";

function ParamChart({ fits, param, label }: { fits: FitRow[]; param: "g0" | "p0" | "tau0"; label: string }) {
  return (
    <ScientificChart
      figureId={label}
      exportName={`depdf-${param}-drift`}
      option={buildDepdfParamOption(fits, param, label)}
      height={240}
      showExports={false}
    />
  );
}

export function DepdfPanel({ fits }: { fits: FitRow[] }) {
  const { copy } = useAppLocale();
  if (fits.length === 0)
    return <p className="text-sm text-muted-foreground">{copy("Aún no hay ajustes. Se deben incorporar los 3 niveles de una visita.", "No fits yet. A fit needs all 3 levels of a visit ingested.")}</p>;
  const sorted = [...fits].sort((a, b) => a.visit_ordinal - b.visit_ordinal);
  return (
    <div className="space-y-6">
      <ScientificChart
        figureId={copy("Curvas DEPDF de no falla", "DEPDF Nonfailure Curves")}
        exportName="depdf-nonfailure-curves"
        option={buildDepdfCurveOption(sorted)}
        height={420}
        caption={copy("Curvas de probabilidad DEPDF de no falla humana de Suhir por visita ajustada. El modelo del backend genera los puntos, que se representan sin cálculos del modelo en el cliente.", "Suhir DEPDF human nonfailure probability curves by fitted visit. Curve points are generated by the backend model and rendered without client-side model math.")}
      />
      <div>
        <h3 className="mb-2 text-sm font-semibold text-foreground">{copy("Parámetros ajustados entre visitas", "Fitted parameters across visits")}</h3>
        <div className="grid grid-cols-1 gap-3 xl:grid-cols-3">
          <ParamChart fits={sorted} param="g0" label={copy("G0 MWL basal", "G0 baseline MWL")} />
          <ParamChart fits={sorted} param="p0" label={copy("P0 no falla basal", "P0 baseline nonfailure")} />
          <ParamChart fits={sorted} param="tau0" label={copy("Tau0 MTTF basal", "Tau0 baseline MTTF")} />
        </div>
      </div>
    </div>
  );
}
