"use client";

import { ScientificChart } from "@/components/charts/EChart";
import { buildDepdfCurveOption, buildDepdfParamOption } from "@/lib/figures";
import type { FitRow } from "@/types";

function ParamChart({ fits, param, label }: { fits: FitRow[]; param: "g0" | "p0" | "tau0"; label: string }) {
  return (
    <ScientificChart
      figureId={label}
      exportName={`depdf-${param}-drift`}
      option={buildDepdfParamOption(fits, param, label)}
      height={240}
      showExports={false}
    />
  );
}

export function DepdfPanel({ fits }: { fits: FitRow[] }) {
  if (fits.length === 0)
    return <p className="text-sm text-muted-foreground">No fits yet. A fit needs all 3 levels of a visit ingested.</p>;
  const sorted = [...fits].sort((a, b) => a.visit_ordinal - b.visit_ordinal);
  return (
    <div className="space-y-6">
      <ScientificChart
        figureId="DEPDF Nonfailure Curves"
        exportName="depdf-nonfailure-curves"
        option={buildDepdfCurveOption(sorted)}
        height={420}
        caption="Suhir DEPDF human nonfailure probability curves by fitted visit. Curve points are generated by the backend model and rendered without client-side model math."
      />
      <div>
        <h3 className="mb-2 text-sm font-semibold text-foreground">Fitted parameters across visits</h3>
        <div className="grid grid-cols-1 gap-3 xl:grid-cols-3">
          <ParamChart fits={sorted} param="g0" label="G0 baseline MWL" />
          <ParamChart fits={sorted} param="p0" label="P0 baseline nonfailure" />
          <ParamChart fits={sorted} param="tau0" label="Tau0 baseline MTTF" />
        </div>
      </div>
    </div>
  );
}
