import { z } from "zod";
import type { AircraftClass } from "@fac-isr/safety-kernel";

export type Kilograms = number & { readonly __unit: "kg" };
export type Configuration = "unarmed-isr" | "unarmed-support" | "armed" | "strike";
const id = z.string().trim().min(1);
const utc = z.string().regex(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,3}))?Z$/).refine((v) => { const m = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,3}))?Z$/.exec(v); if (!m) return false; const d = new Date(v); return Number.isFinite(d.getTime()) && d.getUTCFullYear() === +m[1] && d.getUTCMonth() + 1 === +m[2] && d.getUTCDate() === +m[3] && d.getUTCHours() === +m[4] && d.getUTCMinutes() === +m[5] && d.getUTCSeconds() === +m[6]; });
const finiteNonnegative = z.number().finite().nonnegative();
const raw = z.record(z.union([z.string(), z.number().finite(), z.boolean()]));

export interface UASSystem { id: string; manufacturer: string; model: string; aircraftClass: AircraftClass; mtowKg: Kilograms; configuration: Configuration; approvedConfigurationId: string; approvedSoftwareBaseline?: string; compatibleGcsIds?: readonly string[]; batteryId?: string; evidenceRefs: readonly string[]; rawManufacturerValues?: Record<string, string | number | boolean> }
export interface PayloadConfiguration { id: string; compatibleAircraftIds: readonly string[]; massKg: number; powerW: number; thermalLimitC: number; approvedMassKg: number; approvedPowerW: number; approvedThermalLimitC: number; configurationHash: string; approvedConfigurationHash: string; approvedConfigurationId: string; evidenceRefs: readonly string[] }
export interface GCSConfiguration { id: string; compatibleAircraftIds: readonly string[]; configurationHash: string; approvedConfigurationHash: string; approvedConfigurationId: string; softwareBaseline: string; evidenceRefs: readonly string[] }
export interface BatteryInput { serialNumber: string; aircraftCompatibility: readonly string[]; status: "released" | "restricted" | "quarantined" }
export interface ConfigurationEvidence { current: boolean; approved: boolean; accepted?: boolean; evidenceRefs: readonly string[]; acceptedEvidenceRefs: readonly string[] }
export interface CapabilityRequirement { useCase: "operational" | "airworthiness" | "release" | "research"; conditions: Record<string, unknown>; hard?: boolean }
export interface ConfigurationResult { status: "pass" | "blocked" | "unknown"; reasons: readonly string[]; evidenceRefs: readonly string[] }
export interface CapabilityResult { status: "pass" | "blocked" | "unknown"; reason: string; evidenceRefs: readonly string[] }
export interface CapabilityBaseline { id: string; vendor: string; model: string; capabilities: readonly string[] }
export interface CapabilityComparison { differences: readonly string[] }
export interface CapabilityClaim { id: string; subjectId: string; capability: "vfr" | "ifr" | "vlos" | "evlos" | "bvlos" | "daa" | "c2" | "gnss-integrity" | "payload"; value: string | number | boolean; units?: string; operatingConditions: Record<string, string | number | boolean>; evidenceRefs: string[]; confidence: "verified" | "qualified" | "vendor-claimed" | "research-only"; validFromUtc: string; validToUtc?: string }
export interface Discrepancy { id: string; description: string; severity: "minor" | "major" | "critical"; disposition: "open" | "approved-deferred" | "resolved"; evidenceRefs: readonly string[] }
export interface MaintenanceRelease { aircraftId: string; configurationHash: string; inspectionDueAtUtc: string; openDiscrepancies: readonly Discrepancy[]; minimumEquipmentSatisfied: boolean; batteryRelease: "released" | "restricted" | "quarantined"; payloadRelease: "released" | "restricted" | "removed"; softwareBaseline: string; authorizedBy: string; decision: "released" | "blocked"; signedAtUtc: string }

const UASSchema = z.object({ id, manufacturer: id, model: id, aircraftClass: z.enum(["IA", "IB", "IC", "II", "III"]), mtowKg: finiteNonnegative.positive().transform((v) => v as Kilograms), configuration: z.enum(["unarmed-isr", "unarmed-support", "armed", "strike"]), approvedConfigurationId: id, approvedSoftwareBaseline: id.optional(), compatibleGcsIds: z.array(id).optional(), batteryId: id.optional(), evidenceRefs: z.array(id).min(1, "evidence is required"), rawManufacturerValues: raw.optional() }).strict();
export const PayloadConfigurationSchema = z.object({ id, compatibleAircraftIds: z.array(id).min(1), massKg: finiteNonnegative, powerW: finiteNonnegative, thermalLimitC: z.number().finite(), approvedMassKg: finiteNonnegative, approvedPowerW: finiteNonnegative, approvedThermalLimitC: z.number().finite(), configurationHash: id, approvedConfigurationHash: id, approvedConfigurationId: id, evidenceRefs: z.array(id).min(1) }).strict();
export const GCSConfigurationSchema = z.object({ id, compatibleAircraftIds: z.array(id).min(1), configurationHash: id, approvedConfigurationHash: id, approvedConfigurationId: id, softwareBaseline: id, evidenceRefs: z.array(id).min(1) }).strict();
const ClaimSchema = z.object({ id, subjectId: id, capability: z.enum(["vfr", "ifr", "vlos", "evlos", "bvlos", "daa", "c2", "gnss-integrity", "payload"]), value: z.union([z.string(), z.number().finite(), z.boolean()]), units: z.string().trim().min(1).optional(), operatingConditions: raw, evidenceRefs: z.array(id), confidence: z.enum(["verified", "qualified", "vendor-claimed", "research-only"]), validFromUtc: utc, validToUtc: utc.optional() }).strict().superRefine((value, ctx) => { if ((value.confidence === "verified" || value.confidence === "qualified") && value.evidenceRefs.length === 0) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["evidenceRefs"], message: "evidence is required for verified or qualified claims" }); if (value.validToUtc && Date.parse(value.validToUtc) <= Date.parse(value.validFromUtc)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["validToUtc"], message: "validity end must be after start" }); });
const DiscrepancySchema = z.object({ id, description: id, severity: z.enum(["minor", "major", "critical"]), disposition: z.enum(["open", "approved-deferred", "resolved"]), evidenceRefs: z.array(id).min(1, "evidence is required") }).strict();
const MaintenanceSchema = z.object({ aircraftId: id, configurationHash: id, inspectionDueAtUtc: utc, openDiscrepancies: z.array(DiscrepancySchema), minimumEquipmentSatisfied: z.boolean(), batteryRelease: z.enum(["released", "restricted", "quarantined"]), payloadRelease: z.enum(["released", "restricted", "removed"]), softwareBaseline: id, authorizedBy: id, decision: z.enum(["released", "blocked"]), signedAtUtc: utc }).strict();
export function parseUASSystem(value: unknown): UASSystem { return UASSchema.parse(value); }
export function parseCapability(value: unknown): CapabilityClaim { return ClaimSchema.parse(value); }
export function parseDiscrepancy(value: unknown): Discrepancy { return DiscrepancySchema.parse(value); }
export function parseMaintenanceRelease(value: unknown): MaintenanceRelease { return MaintenanceSchema.parse(value); }
export function parsePayloadConfiguration(value: unknown): PayloadConfiguration { return PayloadConfigurationSchema.parse(value); }
export function parseGCSConfiguration(value: unknown): GCSConfiguration { return GCSConfigurationSchema.parse(value); }
