"""Assemble sentence WAVs generated by the speech skill; no network or keys."""
import hashlib
import json
import re
import sys
from pathlib import Path
import wave

ROOT = Path(__file__).resolve().parents[2]
BASE = ROOT / 'EMAVI'
SOURCE = BASE / 'construccion/runtime/tts-hd'


def prepare():
    SOURCE.mkdir(parents=True, exist_ok=True)
    script = json.loads((BASE / 'video/guion.json').read_text(encoding='utf-8'))
    jobs, segments = [], []
    for chapter in script:
        for i, match in enumerate(re.finditer(r'\S[\s\S]*?(?:[.!?](?=\s|$)|$)', chapter['text'])):
            text = match.group().strip()
            if not text:
                continue
            filename = f"{chapter['id']}-{i:02d}.wav"
            jobs.append({'input': text, 'out': filename})
            segments.append({'chapter': chapter['id'], 'file': filename, 'text': text,
                             'position': match.start(), 'length': len(text)})
    (SOURCE / 'jobs.jsonl').write_text(''.join(json.dumps(j, ensure_ascii=False) + '\n' for j in jobs), encoding='utf-8')
    (SOURCE / 'segments.json').write_text(json.dumps(segments, ensure_ascii=False, indent=2), encoding='utf-8')
    print(f'Prepared {len(jobs)} sentence requests')


def main():
    segments = json.loads((SOURCE / 'segments.json').read_text(encoding='utf-8'))
    script = json.loads((BASE / 'video/guion.json').read_text(encoding='utf-8'))
    report = {'provider': 'OpenAI', 'model': 'tts-1-hd', 'voice': 'onyx',
              'speed': 0.95, 'ai_generated': True,
              'timing_method': 'exact sentence WAV boundaries; 180 ms inter-sentence silence',
              'authorization': 'Explicit user request to send the narration to OpenAI TTS HD',
              'chapters': []}
    for chapter in script:
        selected = [s for s in segments if s['chapter'] == chapter['id']]
        output = BASE / 'video/audio' / (chapter['id'] + '.wav')
        timings, frames, data, expected = [], 0, [], None
        for i, segment in enumerate(selected):
            with wave.open(str(SOURCE / 'sentences' / segment['file']), 'rb') as wav:
                params = (wav.getnchannels(), wav.getsampwidth(), wav.getframerate())
                if expected is not None and params != expected:
                    raise ValueError('Inconsistent WAV format')
                expected = params
                audio = wav.readframes(wav.getnframes())
                # Streaming WAV headers can declare an unknown (0xffffffff) size.
                # Count the decoded PCM actually received, not the header sentinel.
                count = len(audio) // (params[0] * params[1])
                if count == 0:
                    raise ValueError('Empty sentence audio: ' + segment['file'])
            channels, width, rate = params
            timings.append({**segment, 'start_ms': frames / rate * 1000,
                            'end_ms': (frames + count) / rate * 1000,
                            'timing_source': 'OpenAI TTS HD sentence audio duration'})
            data.append(audio)
            frames += count
            if i < len(selected) - 1:
                silence = round(rate * .18)
                data.append(bytes(silence * channels * width))
                frames += silence
        with wave.open(str(output), 'wb') as wav:
            wav.setnchannels(channels)
            wav.setsampwidth(width)
            wav.setframerate(rate)
            wav.writeframes(b''.join(data))
        output.with_suffix('.timing.json').write_text(
            json.dumps(timings, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        report['chapters'].append({'id': chapter['id'], 'seconds': frames / rate,
                                  'sentences': len(selected),
                                  'sha256': hashlib.sha256(output.read_bytes()).hexdigest()})
        print(chapter['id'], round(frames / rate, 2))
    (BASE / 'revision/narracion-hd.json').write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


if __name__ == '__main__':
    prepare() if '--prepare' in sys.argv else main()
