"""Author the source package for the 40-slide EMAVI research lecture.

Only presentation sources are written. No participant records or application
configuration are read or modified. Native Office export is a separate step.
"""
from pathlib import Path
import hashlib
import json
import shutil

ROOT = Path(__file__).resolve().parents[1]
VAULT = Path(r'C:\Users\User\Obsidian\N3o5\Research\ASTRA')
DAY = '2026-09-27'

REFS = {
1: ('Comstock y Arnegard (1992)', 'Comstock, J. R., Jr., & Arnegard, R. J. (1992). The multi-attribute task battery for human operator workload and strategic behavior research. NASA-TM-104174.', 'https://ntrs.nasa.gov/citations/19920007912'),
2: ('Santiago-Espada et al. (2011)', 'Santiago-Espada, Y., Myer, R. R., Latorella, K. A., & Comstock, J. R., Jr. (2011). The Multi-Attribute Task Battery II (MATB-II) software for human performance and workload research: A user’s guide. NASA/TM-2011-217164.', 'https://ntrs.nasa.gov/citations/20110014456'),
3: ('Miller (2010)', 'Miller, W. D., Jr. (2010). The U.S. Air Force-developed adaptation of the Multi-Attribute Task Battery for the assessment of human operator workload and strategic behavior. AFRL-RH-WP-TR-2010-0133.', 'https://ntrl.ntis.gov/NTRL/dashboard/searchResults/titleDetail/ADA537547.xhtml'),
4: ('Cegarra et al. (2020)', 'Cegarra, J., Valéry, B., Avril, E., Calmettes, C., & Navarro, J. (2020). OpenMATB: A Multi-Attribute Task Battery promoting task customization, software extensibility and experiment replicability. Behavior Research Methods, 52, 1980–1990.', 'https://doi.org/10.3758/s13428-020-01364-w'),
5: ('Vogl et al. (2024)', 'Vogl, J., McCurry, C. D., Bommer, S., & Atchley, J. A. (2024). The United States Army Aeromedical Research Laboratory Multi-Attribute Task Battery. Frontiers in Neuroergonomics, 5, 1435588.', 'https://doi.org/10.3389/fnrgo.2024.1435588'),
6: ('Vogl et al. (2025a)', 'Vogl, J., Atchley, J. A., Bommer, S., & McCurry, C. D. (2025). The United States Army Aeromedical Research Laboratory Multi-Attribute Task Battery: Recent developments. 2025 IEEE Research and Applications of Photonics in Defense Conference (RAPID), 1–2.', 'https://doi.org/10.1109/RAPID64712.2025.11151324'),
7: ('Vogl et al. (2025b)', 'Vogl, J., Atchley, J. A., Basso, J., Bommer, S., & McCurry, C. D. (2025, 26 de noviembre). Designing adaptive automation for aviation: Transparency and handoff effects on cognitive workload, situational awareness, and trust. USAARL-TECH-TR--2026-02.', 'https://usaarl.health.mil/assets/docs/techReports/2026-02.pdf'),
8: ('Pontiggia et al. (2024)', 'Pontiggia, A., Gomez-Mérino, D., Quiquempoix, M., Beauchamps, V., Boffet, A., Fabries, P., Chennaoui, M., & Sauvet, F. (2024). MATB for assessing different mental workload levels. Frontiers in Physiology, 15, 1408242.', 'https://doi.org/10.3389/fphys.2024.1408242'),
9: ('Van Benthem et al. (2019)', 'Van Benthem, K., Shanahan, C., Ma, C., Fraser, A., & Herdman, C. M. (2019). The NASA MATB-II predicts prospective memory performance during complex simulated flight. Proceedings of the 20th International Symposium on Aviation Psychology, 67–72. Autoría tomada de la cabecera del texto completo; el registro del repositorio contiene variantes.', 'https://corescholar.libraries.wright.edu/isap_2019/12/'),
10: ('Li et al. (2022)', 'Li, W., Li, R., Xie, X., & Chang, Y. (2022). Evaluating mental workload during multitasking in simulated flight. Brain and Behavior, 12, e2489.', 'https://doi.org/10.1002/brb3.2489'),
11: ('Wang et al. (2024)', 'Wang, P., Houghton, R., & Majumdar, A. (2024). Detecting and predicting pilot mental workload using heart rate variability: A systematic review. Sensors, 24, 3723.', 'https://doi.org/10.3390/s24123723'),
12: ('Che et al. (2025)', 'Che, X., Tang, R., Lin, J., Hui, Q., Zhang, Y., Li, J., & Lan, J. (2025). Three-dimensional (3D) stimuli are always better than two-dimensional (2D) multi-tasking? A high cognitive load in 3D-MATB-II. Behavioural Brain Research, 477, 115322.', 'https://doi.org/10.1016/j.bbr.2024.115322'),
13: ('Rupp et al. (2015)', 'Rupp, M. A., Oppold, P., & McConnell, D. S. (2015). Evaluating input device usability as a function of task difficulty in a tracking task. Ergonomics, 58(5), 722–735.', 'https://doi.org/10.1080/00140139.2014.988755'),
14: ('Kennedy y Parker (2017)', 'Kennedy, L., & Parker, S. H. (2017). Making MATB-II medical: Pilot testing results to determine a novel lab-based, stress-inducing task. Proceedings of the International Symposium on Human Factors and Ergonomics in Health Care. Texto completo local, inicio en p. 201; no se asigna un DOI no verificado.', 'https://fbri.vtc.vt.edu/people-directory/primary-faculty/parker/publications.html'),
15: ('Chancey et al., NASA (2023)', 'Chancey, E. T., Politowicz, M. S., Buck, B. K., Ballard, K. M., Houston, V. E., Le Vie, L. R., Unverricht, J. R., & Chandarana, M. (2023). Foundational human-autonomy teaming research and development in scalable remotely operated advanced air mobility operations: Research model and initial work. AIAA SciTech. NTRS 20220017200; manuscrito depositado en 2022.', 'https://ntrs.nasa.gov/citations/20220017200'),
16: ('NASA, BMed (2025)', 'NASA Human Research Program. (2025, 10 de febrero). Evidence report: Risk of adverse cognitive or behavioral changes and psychiatric disorders leading to in-mission health and performance and long-term health effects. HRP-ER-BMED-HFBP-20250210. Texto completo local.', ''),
17: ('NASA, Sleep (2016)', 'NASA Human Research Program. (2016, 11 de abril). Evidence report: Risk of performance decrements and adverse health outcomes resulting from sleep loss, circadian desynchronization, and work overload. Fecha de aprobación pública en portada del archivo Sleep.pdf.', ''),
18: ('NASA, Team (2022)', 'NASA Human Research Program. (2022, 10 de junio). Risk of performance and behavioral health decrements due to inadequate cooperation, coordination, communication, and psychosocial adaptation within a team. Fecha en portada; archivo local con sufijo 5-9-2024.', ''),
19: ('NASA, HSIA (2021)', 'NASA Human Research Program. (2021, 15 de abril, fecha de portada). Evidence report: Risk of inadequate human-system integration architecture. Archivo local con sufijo 6-13-2023; se conserva la distinción entre fecha declarada y nombre de archivo.', ''),
20: ('NASA, cargas dinámicas (2022)', 'NASA Human Research Program. (2022). Evidence report: Risk of injury due to dynamic loads, Revision A. Archivo OP Dynamic Loads EB FINAL_11-30-22.pdf. Resumen ejecutivo, pp. 12–14.', ''),
21: ('ASTRA, manual v2.6 (2026)', 'Malpica, D. (2026, 25 de septiembre). Manual de Operaciones ASTRA 2026, v2.6, y documentos operativos complementarios actualizados. Plan previsto, sujeto a elegibilidad, recursos y autorización operativa.', ''),
22: ('Liu y Nam (2018)', 'Liu, S., & Nam, C. S. (2018). Quantitative modeling of user performance in multitasking environments. Computers in Human Behavior, 84, 130–140.', 'https://doi.org/10.1016/j.chb.2018.02.035'),
23: ('Daviaux et al. (2019)', 'Daviaux, Y., Bey, C., Arsac, L., Morellec, O., & Lini, S. (2019). Feedback on the use of MATB-II task for modeling of cognitive control levels through psycho-physiological biosignals. International Symposium on Aviation Psychology. Texto completo local.', ''),
24: ('Feltman y Kelley (2024)', 'Feltman, K. A., & Kelley, A. M. (2024). Transcranial direct current stimulation and aviator performance during simulated flight. Aerospace Medicine and Human Performance, 95(1), 5–15. Estudio en simulador Black Hawk; evidencia indirecta para el marco de investigación, no validación de MATB.', 'https://doi.org/10.3357/AMHP.6243.2024'),
}

SLIDES = []
def add(n, title, seconds, oral, refs=(), *, body=None, image=None, columns=None, rows=None, widths=None):
    assert n == len(SLIDES)+5
    item = {'title':title}
    if image:
        item.update(type='image_text',body=body,image={'path':image,'approved':True,'source':'Ilustración conceptual imagegen; ficha y revisión en visuales/AMPLIACION_IMAGEGEN.md. No fotografía documental ni resultado experimental.','alt':title+'; esquema conceptual de investigación.'})
    elif columns:
        item.update(type='table',columns=columns,rows=rows,widths=widths or [],source='Fuentes: '+', '.join(f'[{x}]' for x in refs)+'. Referencias completas en las notas y el archivo bibliográfico.')
    else:
        item.update(type='text',bullets=body)
    SLIDES.append({'n':n,'content':item,'seconds':seconds,'oral':oral,'refs':list(refs)})

add(5,'La pregunta de investigación',45,
    'La pregunta central es cómo cambian el desempeño y la carga percibida cuando una persona debe atender varias tareas aeronáuticas al mismo tiempo, y cómo se relaciona ese cambio con el sueño, el contexto operativo y la respuesta fisiológica. El interés local es construir experimentos comparables entre aviación convencional, operación de UAS y misión análoga. Para ello necesitamos describir la demanda que programamos, observar la conducta que realmente ocurre y conservar las condiciones de adquisición. Estas relaciones se estudiarán en participantes; las pantallas de la aplicación y las verificaciones sintéticas que veremos después no son resultados humanos.',(4,8,21),
    body=['Relacionar demanda, desempeño y fisiología.','Comparar cambios dentro de cada persona.','Estudiar aviación, UAS y misión análoga.','Conservar condiciones y calidad del registro.'])
add(6,'Cuatro tareas concurrentes',55,
    'MATB significa Multi-Attribute Task Battery, o batería de tareas de atributos múltiples. Reúne cuatro demandas que recuerdan actividades aeronáuticas: detectar cambios en sistemas, seguir un objetivo con un control manual, atender comunicaciones dirigidas al propio indicativo y regular recursos. La carga depende de la frecuencia de eventos, su solapamiento, la dinámica del seguimiento y la automatización. La ilustración representa esos dominios; no reproduce la interfaz ni el circuito de combustible de una aeronave. La ventaja experimental es mantener tareas comprensibles para pilotos y personas sin experiencia de vuelo, con resultados separados para cada actividad.',(1,2,4),body='SYSMON: detectar cambios.\n\nTRACK: mantener el seguimiento.\n\nCOMM: atender comunicaciones.\n\nRESMAN: regular recursos. [1, 2]',image='../assets/fac-visuals/01_cuatro_tareas.png')
add(7,'Evolución de MATB',50,
    'La familia comienza con NASA MATB en 1992. La adaptación de la Fuerza Aérea estadounidense documentada en 2010 amplió las opciones de configuración y análisis. MATB-II modernizó la implementación de NASA en 2011. OpenMATB, publicado en 2020, enfatizó el código abierto, los plugins y los escenarios auditables. USAARL MATB añadió transiciones de demanda y control de automatización; las publicaciones de 2024 y 2025 describen sus capacidades y desarrollos. Se trata de una familia de entornos experimentales. Compartir el nombre MATB no hace equivalentes las versiones, los dispositivos, la configuración o las métricas.',(1,2,3,4,5,6),columns=['Año','Implementación','Desarrollo documentado'],rows=[['1992','NASA MATB','Tareas aeronáuticas controlables'],['2010–2011','AF_MATB / NASA MATB-II','Configuración y modernización'],['2020','OpenMATB','Plugins, scripts y replicabilidad'],['2024–2025','USAARL MATB','Demanda dinámica y automatización']],widths=[100,240,490])
add(8,'Comparación de plataformas',65,
    'Esta tabla compara propósitos y capacidades, no establece un ranking de calidad. NASA MATB y MATB-II constituyen el referente de tareas y registro por subtarea. AF_MATB documenta herramientas para configurar escenarios y estudiar estrategias. OpenMATB facilita personalización y revisión del código. USAARL incorpora automatización adaptable y adaptativa, además de sincronización de datos. MATB-FAC articula preparación, tareas y procedencia en nuestro contexto de investigación. La evidencia publicada sobre una versión no se transfiere automáticamente a otra: una traducción, un nuevo joystick, distintos eventos o cambios temporales pueden modificar el desempeño y requieren comprobación.',(1,2,3,4,5,6),columns=['Plataforma','Aporte técnico','Aplicación documentada','Alcance'],rows=[['NASA MATB / II','Cuatro tareas y registro','Carga y desempeño','Referencia experimental'],['AF_MATB','Scripts y configuración','Estrategias de atención','Manual técnico'],['OpenMATB','Código y plugins','Experimentos replicables','Plataforma extensible'],['USAARL MATB','Automatización y LSL','Control, confianza, carga','Estudios específicos'],['MATB-FAC','Diseño y procedencia','Investigación local','Validación humana pendiente']],widths=[155,205,255,215])
add(9,'NASA: tareas y autonomía',60,
    'NASA desarrolló MATB como un conjunto de tareas de referencia para investigar desempeño y carga con control experimental. La guía de MATB-II describe cómo configurar y registrar esas tareas; por sí misma no es un estudio de validez predictiva. Una aplicación posterior interesante es HATTB, la batería de coordinación humano–autonomía presentada por investigadores de NASA para estudiar operaciones UAS con múltiples vehículos. Su filosofía se inspira explícitamente en MATB: tareas suficientemente representativas para investigar, pero accesibles a participantes no expertos y reproducibles entre laboratorios. HATTB es otro banco experimental, no una función que deba atribuirse al MATB-II original.',(1,2,15),body=['NASA: referencia para carga y desempeño. [1, 2]','Control de eventos y registro por subtarea.','HATTB estudia coordinación humano–UAS. [15]','Su diseño retoma la filosofía experimental MATB.'])
add(10,'USAF: demanda y estrategia',55,
    'El informe de Miller, publicado por el Air Force Research Laboratory en 2010, describe AF_MATB. Conserva las cuatro subtareas y añade herramientas para construir scripts, modificar parámetros y analizar el desempeño. La ventana de programación permite anticipar demandas futuras, mientras el estado de las bombas aporta información para organizar la gestión de recursos. Este contexto permite formular preguntas sobre atención, prioridades y estrategias ante tareas simultáneas. El respaldo aquí es un informe técnico de desarrollo y uso. No lo presentaremos como prueba de que la USAF utiliza MATB para certificar aptitud o seleccionar pilotos mediante puntos de corte validados.',(3,),body=['AFRL documentó AF_MATB en 2010. [3]','Scripts y parámetros configurables.','Programación de demandas y estrategias.','Aplicación: investigación de factores humanos.'])
add(11,'US Army: control compartido',75,
    'USAARL MATB permite que la persona active automatización o que el sistema transfiera el control según reglas del experimento. Integra estados de automatización, eventos y resultados con señales externas mediante Lab Streaming Layer, LSL. Un informe de noviembre de 2025 estudió a 24 aviadores del Ejército con un diseño de medidas repetidas que cruzó transparencia de la información y transferencia voluntaria o forzada. Los autores observaron mayor carga en las condiciones transparentes; el efecto multivariado comunicado fue p igual a 0,002 y eta cuadrado 0,35. La transferencia voluntaria favoreció la confianza. El resultado ilustra que añadir información puede tener un coste; no prescribe una interfaz universal para cualquier aeronave.',(5,6,7),columns=['Diseño','Resultado publicado','Interpretación'],rows=[['24 aviadores; 2 × 2','Transparencia × transferencia','Cada piloto probó cuatro condiciones'],['Más transparencia','Mayor carga; p = 0,002; η² = 0,35','Efecto de esta configuración'],['Control voluntario','Mejor perfil de confianza','Control y confianza se estudian juntos'],['Límite','Muestra pequeña; entorno de escritorio','Transferencia operacional por estudiar']],widths=[215,305,310])
add(12,'Evidencia de sensibilidad',65,
    'La validez debe formularse respecto a una interpretación concreta. Para estudiar respuesta a la demanda, la revisión de Pontiggia reunió 19 artículos y encontró que más eventos, más subtareas y mayor solapamiento suelen acompañarse de mayor carga percibida y peor desempeño, especialmente en seguimiento. Sin embargo, solo siete describieron la configuración con suficiente detalle. Un estudio primario de Li y colaboradores, con 26 universitarios varones, combinó tareas, NASA-TLX, electrocardiografía y espectroscopia funcional de infrarrojo cercano. La mayor demanda elevó carga percibida, frecuencia cardíaca y activación prefrontal. Este paradigma difiere del MATB canónico; aporta evidencia convergente sobre multitarea, no validación directa de MATB ni normas locales.',(8,10),columns=['Evidencia','Hallazgo','Condición de interpretación'],rows=[['Revisión: 19 estudios','Sensibilidad a demanda y solapamiento','Configuraciones heterogéneas'],['Descripción suficiente: 7/19','Dificultad para reproducir escenarios','Publicar parámetros y entrenamiento'],['Li et al.: n = 26','Mayor carga, FC y activación prefrontal','Tarea distinta de MATB; universitarios']],widths=[240,300,290])
add(13,'Memoria prospectiva en vuelo',60,
    'La memoria prospectiva es recordar que hay que realizar una acción futura cuando aparece una señal relevante. Van Benthem y colaboradores estudiaron a 51 pilotos en un laboratorio de vuelo visual simulado. Relacionaron resultados de seguimiento, monitoreo y gestión de recursos en MATB-II con el cumplimiento de llamadas de radio asociadas a señales visuales. Encontraron asociaciones predictivas dentro de esa muestra, moduladas por la condición de carga y atributos del piloto. El resumen y la sección de resultados comunican cifras distintas de varianza explicada; por esa razón no presentamos un porcentaje único. No hubo una validación externa que permita convertir esos modelos en un umbral de selección local.',(9,),body=['51 pilotos; vuelo visual simulado. [9]','MATB-II se asoció con memoria prospectiva.','Monitoreo y demanda modifican la relación.','Falta validación externa para uso selectivo.'])
add(14,'Aplicaciones internacionales',60,
    'La utilidad del paradigma también aparece al modificar interfaces y contextos. Rupp y colaboradores compararon controles manuales y mostraron que la familiaridad y el entrenamiento deben considerarse al interpretar seguimiento y usabilidad. Che y colaboradores analizaron 49 participantes: separar las tareas en planos de profundidad en realidad virtual se acompañó de peor desempeño y mayor carga frente a la condición bidimensional. Ese resultado no afirma que toda realidad virtual sea inferior; señala una decisión específica de diseño. En medicina, Kennedy y Parker pilotaron una adaptación con diez estudiantes, observando diferencias de NASA-TLX, pero no diferencias significativas en ansiedad de estado. Carga, estrés y rendimiento no son medidas intercambiables.',(12,13,14),columns=['Dominio','Ejemplo','Aprendizaje para investigación'],rows=[['Interfaces de control','Rupp et al.: dispositivos y práctica','Controlar familiaridad y entrenamiento'],['Realidad virtual','Che et al.: 49 participantes','La profundidad puede añadir demanda'],['Formación sanitaria','Kennedy y Parker: 10 estudiantes','Separar carga percibida y estrés']],widths=[190,280,360])
add(15,'Integrar medidas',65,
    'La triangulación combina demanda programada, resultados de la tarea, percepción subjetiva y señales fisiológicas. Cada fuente responde a una pregunta diferente. Los errores y las latencias describen el desempeño; NASA-TLX recoge carga percibida; el electrocardiograma y la HRV describen aspectos de la respuesta fisiológica. La revisión de Wang, con 29 trabajos, encontró relaciones inconsistentes entre HRV y carga del piloto, relacionadas con diferencias de diseño y medición. Por ello no trataremos la HRV como un medidor universal de carga ni como un indicador automático de aptitud. La sincronización temporal, la calidad de señal y el contexto de sueño, movimiento y respiración deben acompañar cualquier análisis.',(10,11,23),body=['Demanda → eventos programados.','Desempeño → errores, latencias y seguimiento.','Percepción → NASA-TLX; fisiología → señales.','HRV: resultados heterogéneos en 29 estudios. [11]'])
add(16,'ASTRA: misión análoga',55,
    'ASTRA significa Aerospace Simulation Training Research Analogs. El manual describe dos misiones secuenciales independientes de aislamiento y confinamiento, cada una de quince días inclusivos. La instalación de referencia es el hábitat análogo lunar de la Fundación Cydonia en el Parque Jaime Duque, Tocancipá. Su superficie aproximada es de 120 metros cuadrados. La meta nominal es de seis tripulantes por misión, condicionada a elegibilidad. La ilustración reúne áreas funcionales descritas en el manual, pero no reproduce un plano constructivo. El análogo estudia convivencia, organización del trabajo y adaptación en condiciones terrestres; no reproduce gravedad lunar ni radiación espacial.',(21,),body='Dos misiones independientes de 15 días.\n\nHábitat Cydonia, Tocancipá; ~120 m².\n\nMeta nominal: seis tripulantes por misión.\n\nPlan previsto; esquema conceptual. [21]',image='../assets/fac-visuals/02_habitat.png')
add(17,'Fundamentos de ASTRA',60,
    'Los informes del Human Research Program de NASA organizan preguntas sobre salud conductual, sueño, trabajo en equipo e integración humano–sistema. ASTRA toma esos dominios como fundamento de investigación, sin asumir que los riesgos o sus magnitudes sean iguales en un hábitat terrestre y en vuelo espacial. El informe conductual de 2025 orienta el seguimiento de cambios cognitivos y conductuales. El informe de sueño de 2016 relaciona pérdida de sueño, desincronización circadiana y sobrecarga. El informe de equipos aborda coordinación, cooperación y comunicación. HSIA integra diseño de tareas, interfaces y apoyo al operador. El documento de cargas dinámicas delimita otro problema físico que este entorno de escritorio no reproduce.',(16,17,18,19,20),columns=['Dominio NASA','Pregunta en el análogo','Medición relacionada'],rows=[['Conducta y cognición','¿Cómo evoluciona la adaptación?','Evaluaciones y bitácoras'],['Sueño y carga','¿Cómo se relacionan descanso y tareas?','Actigrafía, KSS y desempeño'],['Equipos','¿Cómo cambia la coordinación?','Roles, comunicaciones y debriefing'],['Integración humano–sistema','¿Cómo influye el diseño del trabajo?','MATB, interfaces y procedimientos']],widths=[245,320,265])
add(18,'Tripulación y control',55,
    'La misión distribuye seis funciones principales: comandante, datos, ingeniería biomédica, medicina, ingeniería de vuelo y comunicaciones. Las suplencias y apoyos cruzados deben quedar registrados; una función alternativa no significa añadir otro integrante. El Centro de Control de Misión coordina planificación, apoyo y decisiones operativas. CAPCOM organiza el canal de voz con la tripulación. Esta división permite estudiar cómo se mantiene una representación compartida de la situación, cómo se detecta un problema y cómo se distribuye la carga. El seguimiento científico aporta datos, mientras las decisiones sobre seguridad y continuidad permanecen bajo responsabilidad humana. La imagen representa roles genéricos, sin identificar participantes.',(18,19,21),body='Seis funciones con apoyos cruzados.\n\nMCC: planificación, apoyo y seguimiento.\n\nCAPCOM organiza la comunicación.\n\nDecisiones operativas humanas. [21]',image='../assets/fac-visuals/03_tripulacion_mcc.png')
add(19,'Calendario previsto',55,
    'El calendario vigente del manual separa la preparación, la misión activa y el seguimiento posterior. ASTRA uno prevé ingreso el cinco de octubre y egreso el diecinueve; ASTRA dos, ingreso el veintiuno de octubre y egreso el cuatro de noviembre. Las jornadas basales son el veintinueve de septiembre y el veintiocho de septiembre, respectivamente. Por tanto, la distancia temporal entre basal e ingreso es diferente entre grupos y debe conservarse en el análisis. La evaluación postmisión se concentra en el día siguiente al egreso. Estos son hitos documentales previstos; la presentación no acredita que las evaluaciones o las misiones ya hayan ocurrido.',(21,),columns=['Fase','ASTRA 1','ASTRA 2'],rows=[['Basal experimental','29 septiembre','28 septiembre'],['Ingreso / DM1','5 octubre','21 octubre'],['Egreso / DM15','19 octubre','4 noviembre'],['Postmisión / D+1','20 octubre','5 noviembre']],widths=[250,290,290])
add(20,'La jornada de misión',55,
    'La misión organiza oportunidades protegidas de sueño, alimentación, ejercicio, trabajo científico, mantenimiento y convivencia. La oportunidad nominal de sueño es de ocho horas, entre las veintidós treinta y las seis treinta. No equivale a afirmar que cada persona dormirá ocho horas: duración y fragmentación se medirán. Las actividades extravehiculares simuladas se programan en los días de misión seis y doce, con preparación, verificación de equipos, apoyo y recuperación. Son salidas terrestres en un perímetro delimitado. La bitácora nominal de treinta minutos y el debriefing aportan contexto para interpretar cambios de carga y eventos. Los horarios pueden ajustarse por seguridad, registrando la desviación.',(17,21),body='Sueño protegido: 22:30–06:30.\n\nCiencia, ejercicio y mantenimiento.\n\nEVA simuladas: DM6 y DM12.\n\nDebriefing y bitácora diaria. [21]',image='../assets/fac-visuals/04_eva.png')
add(21,'Medición multimodal',60,
    'El manual integra fisiología, sueño y actividad, evaluación psicológica, cognición y registro operativo. El Polar H10 aporta los intervalos entre latidos; ActiGraph registra acelerometría y, en la cadena prevista, recibe los intervalos R–R del H10 emparejado. La descarga pasa por ActiLife en un portátil y debe comprobarse antes del despliegue. No se calcula HRV a partir de una serie de frecuencia cardíaca promedio. Las fases tampoco son simultáneas por definición: fisiología utiliza DM7 y psicología DM8. La comparación debe usar fechas y ventanas reales. La ilustración muestra colocación y contexto; la cadena de adquisición se explica en el texto editable y no representa un registro real.',(11,21),body='H10: intervalos R–R.\n\nActiGraph: movimiento y recepción R–R.\n\nActiLife: verificar la descarga.\n\nPsicología, cognición y bitácoras. [21]',image='../assets/fac-visuals/05_medicion-v2.png')
add(22,'Ocho visitas MATB previstas',65,
    'La versión 2.6 del manual define ocho visitas MATB por persona: basal, seis durante la misión y una después del egreso. Cada visita reserva noventa minutos e incluye tres bloques de quince minutos de tarea, además de preparación, pausas, cuestionarios y cierre. El orden de baja, media y alta demanda se contrabalancea; no se impone siempre una secuencia ascendente. Los días intramisión son dos, cuatro, siete, diez, trece y quince. Las etiquetas analíticas pre, medio y final corresponden a un subconjunto, no eliminan las otras visitas. Más adelante distinguiremos este protocolo previsto del perfil actualmente registrado en el software.',(8,21),columns=['Momento','Visitas del manual','Organización de la sesión'],rows=[['Antes de misión','V0: basal','Familiarización y referencia'],['Durante la misión','V1–V6: DM2, 4, 7, 10, 13, 15','Tres bloques × 15 min'],['Después del egreso','V7: D+1','Mismo esquema de medición'],['Cada visita','Reserva de 90 min','Demanda contrabalanceada']],widths=[205,325,300])
add(23,'Relacionar las trayectorias',55,
    'El análisis vinculará persona, visita, bloque, condición y fecha real. Una pregunta es si cambios de sueño o somnolencia se asocian con diferencias posteriores de desempeño o carga percibida. Otra es cómo varía la respuesta fisiológica ante la misma demanda programada a lo largo de la misión. Deben considerarse práctica, diferencias de horario, calidad de señal y datos faltantes. Los dos grupos son pequeños; los análisis longitudinales serán exploratorios y mostrarán trayectorias individuales e incertidumbre. La integración permite formular hipótesis y caracterizar factibilidad. No permite atribuir causalidad a cualquier correlación ni construir automáticamente una puntuación de preparación operacional.',(8,11,21),body=['Persona → visita → bloque → condición.','Fechas reales, sueño y contexto de actividad.','Controlar práctica y calidad de las señales.','Análisis exploratorio e incertidumbre explícita.'])

# The seven documentary screenshots remain intact and are not replaced by AI.
CAPTURES = [
('Elegir una actividad','01_catalogo.png','El catálogo presenta las tareas y sus requisitos.\n\nDistingue práctica y participación en un estudio.\n\nCaptura local de demostración.',
'El catálogo organiza las actividades disponibles y muestra sus requisitos. Su función es orientar la preparación de la sesión: elegir una tarea, conocer los dispositivos necesarios y distinguir práctica de participación en un estudio. La captura procede del entorno local de demostración documentado el veintiuno de septiembre. No muestra resultados de participantes. Antes de un estudio, la actividad elegida debe corresponder a la versión y al protocolo aprobados. La existencia de una opción en la pantalla no demuestra que su adquisición, temporización o interpretación ya estén calificadas para todos los contextos.'),
('Diseñar el escenario','02_diseno.png','La línea temporal organiza tareas y eventos.\n\nDuración y semilla definen la configuración.\n\nEl registro conserva su procedencia.',
'El diseñador hace explícita la demanda experimental mediante tareas y eventos distribuidos en el tiempo. Duración, parámetros y semilla permiten conservar una configuración reproducible. Este paso conecta con un problema observado en la literatura: describir suficientemente lo que se presentó al participante. Guardar el escenario ayuda a revisar cuántos eventos se programaron y cómo se solaparon. La trazabilidad del archivo es una propiedad técnica. La dificultad que una persona experimenta requiere medición y puede cambiar según práctica, dispositivo, fatiga o contexto, aunque los parámetros programados sean idénticos.'),
('Preparar OpenMATB','03_openmatb.png','La consola configura las cuatro tareas.\n\nLa vista previa apoya la preparación.\n\nLa ejecución de tareas corresponde a OpenMATB.',
'La consola prepara el entorno de cuatro tareas y permite revisar su presentación antes de ejecutar. OpenMATB aporta la implementación de las tareas, mientras la consola organiza configuración y procedencia. Es importante conservar esa distinción para atribuir correctamente las funciones de cada componente. La revisión previa debe incluir idioma, audio, controles, instrucciones y compatibilidad de dispositivos. Las capturas son evidencia documental de una interfaz disponible en el checkout registrado; no sustituyen una comprobación del tiempo físico de los estímulos ni un estudio de validez con participantes.'),
('Somnolencia y vigilancia','04_kss.png','KSS registra somnolencia subjetiva.\n\nPVT evalúa vigilancia en una tarea específica.\n\nEjemplo local con participante de demostración.',
'La escala de somnolencia de Karolinska, KSS, recoge el estado subjetivo de somnolencia. La tarea de vigilancia psicomotora, PVT, obtiene respuestas en una situación definida de atención sostenida. Estas medidas complementan el contexto de la sesión, pero no son equivalentes entre sí ni se deben fusionar automáticamente en un diagnóstico. La secuencia visible enlaza preparación, instrucciones y actividad. En la aplicación de investigación habrá que conservar el momento exacto de cada medida, la versión del instrumento y su relación temporal con el bloque MATB. La captura corresponde a una persona de demostración, sin datos humanos adquiridos.'),
('Supervisar una misión UAS','05_suas.png','Mapa, flota, alertas y controles.\n\nRegistro de eventos para revisión.\n\nLa captura procede de una prueba sintética.',
'UAS significa sistema de aeronave no tripulada. La vista de misión reúne un mapa, elementos de flota, alertas y controles para un escenario de investigación. Permite estudiar cuestiones distintas del seguimiento manual: distribución de atención entre vehículos, supervisión de automatización y respuesta a eventos. La imagen corresponde a una prueba técnica sintética. El camino científico consiste en documentar las demandas del escenario, verificar sus registros y después evaluar sus relaciones con medidas humanas. La apariencia operacional de un mapa no acredita por sí misma fidelidad de vuelo, validez de selección o transferencia a una operación real.'),
('Revisar la evidencia','06_evidencia.png','La carga reúne manifiestos y eventos.\n\nCada métrica conserva su evidencia.\n\nEjemplo sintético de referencia.',
'El inspector conecta configuraciones, eventos y observaciones temporales. Esto facilita revisar de dónde sale una métrica y cuáles son sus condiciones de elegibilidad. Si se cambia una regla de análisis, la procedencia permite identificar qué registros fueron usados y recomputar el resultado. En el ejemplo, la evidencia es sintética y sirve para comprobar comportamiento del sistema. Un informe técnicamente reproducible todavía puede contener señales de mala calidad o una interpretación científica inadecuada. Por eso deben mantenerse tanto la revisión del registro como la justificación de las métricas y sus límites.'),
('Del evento al resultado','07_evento.png','Evento y base temporal permanecen vinculados.\n\nSe conservan motivos de elegibilidad.\n\nLa exportación permite recomputar.',
'La revisión de un evento permite recorrer la cadena entre estímulo, respuesta y métrica. La base temporal y los motivos de elegibilidad son necesarios para interpretar retrasos, pérdidas o registros incompletos. Exportar esa cadena facilita auditoría y recomputación fuera de la interfaz. La demostración técnica existente recomputó once métricas sintéticas, pero registró una discrepancia en la huella de dependencias. Ese antecedente no se transforma en una certificación del entorno actual. La siguiente etapa de investigación requiere cerrar la calificación temporal y de adquisición, ejecutar el protocolo humano y analizar sus resultados con incertidumbre explícita.'),
]
for n,(title,file,body,oral) in enumerate(CAPTURES,24):
    add(n,title,35,oral,body=body,image='../capturas/'+file)
    SLIDES[-1]['content']['image']['source']='Captura documental local, 2026-09-21; capturas/procedencia.json. Datos de demostración o sintéticos; sin registros de participantes.'
    SLIDES[-1]['content']['image']['alt']=title+'; captura documental de la aplicación.'

add(31,'Aviación convencional',50,
    'En aviación convencional, MATB permite aislar preguntas sobre reparto de atención, seguimiento, comunicaciones y detección de anomalías. Podemos comparar secuencias de instrucciones, cambios de interfaz o condiciones de descanso bajo una demanda documentada. El beneficio inmediato es disponer de una situación experimental repetible y de mediciones vinculadas al evento. La relación con desempeño aeronáutico debe estudiarse después con criterios externos, como tareas específicas de un simulador de vuelo. La imagen une contextos de investigación de aviación convencional y UAS; no afirma que el mismo instrumento represente por igual todas sus exigencias físicas, perceptivas o decisionales.',(2,9,13),body='Atención entre instrumentos y comunicaciones.\n\nSeguimiento manual y detección de anomalías.\n\nContraste posterior con tareas de vuelo. [2, 9]',image='../assets/fac-visuals/06_aviacion_uas.png')
add(32,'Operación UAS',45,
    'En una estación UAS, la carga puede depender del número de vehículos supervisados, la concurrencia de alertas, el modo de control y la confianza en la automatización. La experiencia de NASA con HATTB y de USAARL con transferencias de control ayuda a formular experimentos locales sobre estas variables. No basta con aumentar el número de pantallas para representar una operación compleja. Debemos especificar decisiones, información disponible, tiempos y consecuencias simuladas, y medir tanto aciertos como omisiones y recuperación después de una alerta. La integración con fisiología se plantea como investigación multimodal, conservando la contribución independiente de cada medida.',(5,7,15),body=['Supervisión de vehículos y alertas concurrentes.','Transferencias entre persona y automatización.','Conciencia situacional y confianza.','Diseño experimental inspirado en HATTB. [15]'])
add(33,'Beneficios entre dominios',50,
    'El desarrollo local permite conectar preguntas de varios dominios sin reducirlos a una única puntuación. En factores humanos, se estudia cómo una interfaz cambia el desempeño. En medicina aeroespacial, se describe el contexto de sueño, somnolencia y respuesta fisiológica. En psicología, se examinan atención, memoria y estrategias. En formación, se pueden comparar métodos de práctica y retroalimentación. La aportación común es contar con protocolos documentados, resultados trazables y posibilidades de replicación. Los beneficios que presentamos son capacidades de investigación y preguntas evaluables. Cualquier efecto sobre seguridad, selección o eficacia del entrenamiento requiere sus propios estudios.',(8,11,13,14,21,22),columns=['Dominio','Pregunta local','Producto verificable'],rows=[['Factores humanos','¿Qué interfaz facilita la tarea?','Comparación de errores y tiempos'],['Medicina aeroespacial','¿Cómo influye el contexto fisiológico?','Registros sincronizados y calidad'],['Psicología y cognición','¿Qué estrategias cambian?','Patrones por tarea y condición'],['Formación','¿Qué práctica produce transferencia?','Estudios de aprendizaje y retención']],widths=[205,310,315])
add(34,'Desarrollo por etapas',55,
    'Una plataforma de escritorio permite empezar por preguntas cognitivas y de interacción que no requieren movimiento multiaxial. Las aceleraciones, vibraciones, cargas biomecánicas y estímulos vestibulares requieren recursos y validaciones adicionales. La ruta propuesta comienza por temporización, configuración y calidad de adquisición; continúa con factibilidad humana, sensibilidad a la demanda y fiabilidad entre sesiones; después examina validez respecto a criterios aeronáuticos. Solo una etapa posterior podría evaluar utilidad para selección o entrenamiento, con normas, evaluación de sesgos y transferencia. Este orden produce evidencia acumulativa sin presentar las funciones actuales del software como pruebas psicométricas ya validadas.',(8,9,20),columns=['Etapa','Pregunta de verificación','Resultado esperado'],rows=[['1. Técnica','¿Qué se presenta y registra?','Tiempo y adquisición calificados'],['2. Humana','¿Es sensible y reproducible?','Factibilidad, fiabilidad y efectos'],['3. Transferencia','¿Se relaciona con tareas aeronáuticas?','Validación externa e incertidumbre'],['4. Aplicación específica','¿Sirve para entrenar o seleccionar?','Utilidad, normas y evaluación de sesgos']],widths=[170,345,315])
add(35,'Estado y conciliación',55,
    'El estado actual se presenta en tres planos. La aplicación dispone de funciones e interfaces documentadas y de verificaciones técnicas sintéticas fechadas. El manual operativo define el estudio humano previsto de ocho visitas. Sin embargo, el perfil astra-2026 del código registra tres visitas: T0, DM8 y DM15. Además, los tres momentos analíticos del manual corresponden a V0, V3 y V6, con DM7 como visita intermedia; no son equivalentes al perfil de software. Esta ampliación de la presentación no modifica protocolos ni bases de datos. La conciliación debe resolverse antes del despliegue correspondiente, junto con la comprobación de adquisición y tiempo físico.',(21,),body=['Funciones disponibles y verificación sintética.','Manual v2.6: ocho visitas V0–V7.','Perfil astra-2026: T0 / DM8 / DM15.','Conciliar antes de ejecutar el protocolo humano.'])
add(36,'Conclusiones',45,
    'La literatura muestra que MATB es una familia de entornos útiles para formular y controlar preguntas sobre multitarea, interfaces y automatización. Su interpretación depende de la versión, la configuración, la población y el criterio evaluado. ASTRA ofrece un contexto longitudinal terrestre para relacionar tareas, fisiología, sueño y adaptación dentro de cada persona. El desarrollo local puede conectar aviación convencional y UAS mediante preguntas comunes, conservando las diferencias operacionales. El siguiente resultado científico no será una pantalla más, sino un protocolo ejecutable, mediciones de calidad y evidencia humana que permita estimar fiabilidad, validez y transferencia con límites explícitos.',(4,8,21),body=['MATB permite controlar preguntas de multitarea.','ASTRA aporta seguimiento y contexto operativo.','La integración exige trazabilidad y calidad.','El desarrollo avanza con evidencia humana.'])

for n,title,ids in [(37,'Referencias: plataformas',[1,2,3,4,5,6,7,15]),(38,'Referencias: evidencia',[8,9,10,11,12,13,14,23]),(39,'Referencias: ASTRA',[16,17,18,19,20,21,22,24])]:
    add(n,title,0,'Referencias de consulta. La bibliografía completa, los localizadores y la revisión crítica se entregan como archivos complementarios.',ids,columns=['Fuente','Documento o contribución'],rows=[[f'[{x}] {REFS[x][0]}',{
1:'MATB original; NASA-TM-104174',2:'Guía MATB-II; NASA/TM-2011-217164',3:'AF_MATB; AFRL-RH-WP-TR-2010-0133',4:'OpenMATB; doi: 10.3758/s13428-020-01364-w',5:'USAARL; doi: 10.3389/fnrgo.2024.1435588',6:'Desarrollos USAARL; IEEE RAPID 2025',7:'Automatización; USAARL-TECH-TR--2026-02',8:'Configuración y demanda; revisión de 19 estudios',9:'Memoria prospectiva; ISAP 2019, 67–72',10:'Multitarea, fNIRS y ECG; doi: 10.1002/brb3.2489',11:'HRV del piloto; doi: 10.3390/s24123723',12:'Profundidad y carga; doi: 10.1016/j.bbr.2024.115322',13:'Dispositivos de control; Ergonomics 58, 722–735',14:'Adaptación médica; piloto de 10 estudiantes',15:'HATTB; NASA NTRS 20220017200',16:'Cambios cognitivos y conductuales',17:'Sueño, desincronización y sobrecarga',18:'Cooperación, coordinación y comunicación',19:'Integración humano–sistema',20:'Riesgo por cargas dinámicas; Rev. A',21:'Manual v2.6 y documentos operativos',22:'Modelado de desempeño multitarea',23:'Control cognitivo y límites de estandarización',24:'Simulador Black Hawk; evidencia indirecta'}[x]] for x in ids],widths=[305,525])

def write_json(path, value):
    path.write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

def main():
    assert len(SLIDES)==35
    history=ROOT/'fuentes/historico_20260923'; history.mkdir(exist_ok=True)
    for name in ['manifest.json','notas.json','politica_clasificacion.md','aprobacion_politica.json']:
        if not (history/name).exists(): shutil.copy2(ROOT/'fuentes'/name,history/name)
    old=json.loads((history/'manifest.json').read_text(encoding='utf-8-sig'))
    manifest={'schema_version':'1.1.0-emavi','privacy':{'branch':'qualified','value':'Público Clasificado','notice_placement':'opening_only'},'title_page':old['title_page'],'agenda':['MATB: evidencia y aplicaciones','ASTRA: fundamentos y misión','Preparación y trazabilidad','Desarrollo de investigación local'],'content':[s['content'] for s in SLIDES]}
    manifest['title_page']['title']='MATB Y ASTRA\nINVESTIGACIÓN AERONÁUTICA'
    write_json(ROOT/'fuentes/manifest.json',manifest)
    notes=[{'title':'Apertura institucional','seconds':0,'oral':'Pantalla institucional de apertura.','sources':'Plantilla FAC, lámina 1.'},{'title':'Aviso inicial','seconds':5,'oral':'Aviso inicial de información pública clasificada.','sources':'Plantilla FAC, lámina 4; instrucción del usuario de mostrar la clasificación solo al inicio.'},{'title':'MATB y ASTRA','seconds':25,'oral':'Soy Diego L. Malpica, especialista en Medicina Aeroespacial. Presentaré la evidencia internacional sobre MATB, el diseño previsto de ASTRA y las preguntas que podemos investigar al integrar tareas aeronáuticas, fisiología y desempeño cognitivo en nuestro contexto.','sources':'Autoría institucional conservada del material original.'},{'title':'Agenda','seconds':30,'oral':'Primero revisaremos qué representa MATB y qué evidencia existe sobre sus aplicaciones. Después explicaremos ASTRA, recorreremos la preparación y trazabilidad de una sesión y terminaremos con una ruta de investigación para aviación convencional, UAS y factores humanos.','sources':'Estructura docente de la ampliación.'}]
    for s in SLIDES:
        notes.append({'title':s['content']['title'],'seconds':s['seconds'],'oral':s['oral'],'sources':'\n'.join(f'[{r}] {REFS[r][1]} {REFS[r][2]}' for r in s['refs']) or 'Capturas documentales: EMAVI/capturas/procedencia.json; informes técnicos de septiembre de 2026. No datos humanos.'})
    notes.append({'title':'Cierre institucional','seconds':15,'oral':'Gracias. Quedan abiertas las preguntas sobre diseño experimental, medición y desarrollo de las próximas etapas de investigación.','sources':'Plantilla FAC, lámina 12.'})
    total=sum(n['seconds'] for n in notes)
    # Allocate the remaining planned time to the seven documentary demonstrations.
    remaining=1740-total
    assert remaining>=0, total
    for i in range(remaining): notes[23+i%7]['seconds']+=1
    assert len(notes)==40 and sum(n['seconds'] for n in notes)==1740
    write_json(ROOT/'fuentes/notas.json',notes)
    write_json(ROOT/'fuentes/aprobacion_politica.json',{'approved':True,'requested_classification':'Público Clasificado','policy':'politica_clasificacion.md','status':'approved_by_user','approved_on':DAY,'approval_source':'User requested classification only on one opening slide, then instructed: Implement the proposed plan.','notice_placement':'opening_only','scope':'Graphic policy for the expanded EMAVI presentation; classification retained. No new authorization to distribute or publish is inferred.','previous_record':'historico_20260923/aprobacion_politica.json'})
    (ROOT/'fuentes/politica_clasificacion.md').write_text('# Política gráfica EMAVI · revisión 27-09-2026\n\nClasificación conservada: **Público Clasificado**, rama `qualified`.\n\nEl usuario solicitó retirar el rótulo de las diapositivas y conservarlo únicamente en una lámina inicial; aprobó la implementación del plan ampliado. Esta instrucción sustituye la propagación gráfica del 23 de septiembre.\n\n1. Conservar íntegro el aviso de la diapositiva 4 de la plantilla, como diapositiva 2 de la presentación. Seleccionar únicamente Público Clasificado.\n2. No añadir etiquetas a portada, agenda o contenido. No repetir el aviso antes del cierre.\n3. Conservar apertura, cierre, marcas, fondos y líneas institucionales.\n4. El arquetipo local `table` usa el área libre, con tabla editable dentro de x=60–900 y y=120–444 pt, más fuente en y=449–470 pt. Mantiene título y línea del arquetipo 10. Es la extensión local necesaria para la tabla comparativa aprobada.\n5. Verificar exactamente una diapositiva con el rótulo visible en PPTX y PDF: la 2. Metadatos y registro de clasificación se conservan.\n\nLa política anterior y sus fuentes se conservan en `historico_20260923/`. La plantilla y la habilidad instalada permanecen intactas. Esta decisión gráfica no reclasifica el material ni autoriza su distribución.\n',encoding='utf-8')
    md=['# Presentación EMAVI ampliada','',f'40 diapositivas. Guion programado: 29:00; sin ensayo humano. Fecha: {DAY}.','']
    oral=['# Notas del ponente · EMAVI ampliada','','Tiempo programado: 29:00. Video y preguntas independientes. Duración estimada, no ensayo humano.','']
    for i,n in enumerate(notes,1):
        oral.extend([f'## {i}. {n["title"]} · {n["seconds"]} s','',n['oral'],'','**Fuentes y apoyo:** '+n['sources'],''])
        md.extend([f'## {i}. {n["title"]}',''])
        if 5<=i<=39:
            c=SLIDES[i-5]['content']
            if c['type']=='table':
                md.extend(['| '+' | '.join(c['columns'])+' |','| '+' | '.join(['---']*len(c['columns']))+' |'])
                md.extend('| '+' | '.join(row)+' |' for row in c['rows'])
            elif c['type']=='text': md.extend('- '+x for x in c['bullets'])
            else:md.extend([c['body'],'',f'Imagen: {c["image"]["path"]}'])
            md.extend(['','Fuentes: '+(', '.join(f'[{r}]' for r in SLIDES[i-5]['refs']) or 'Procedencia de capturas e informes técnicos locales.'),''])
        elif i==2:md.extend(['Única diapositiva con el aviso Público Clasificado.',''])
    (ROOT/'entregables/Contenido_diapositivas.md').write_text('\n'.join(md),encoding='utf-8')
    (ROOT/'entregables/Notas_del_ponente_es.md').write_text('\n'.join(oral),encoding='utf-8')
    bib=['# Referencias de la ampliación EMAVI','','Fecha de revisión: 27 de septiembre de 2026. Numeración idéntica a diapositivas y notas. Las fechas de portada y los nombres de archivo se distinguen cuando no coinciden.','']
    for k,(_,ref,url) in REFS.items():bib.extend([f'{k}. {ref}'+(f' {url}' if url else ''),''])
    bib.extend(['## Alcance bibliográfico','','Las referencias 1–20 y 22–24 son literatura o documentación técnica; [21] es planificación local. Los seis PDF NASA tienen hash y ubicación de origen en `../fuentes/registro_fuentes.json`. Las dos notas de síntesis militar y el enlace pendiente de descarga no constituyen evidencia primaria. Véase la matriz y revisión crítica para resultados, localizadores y exclusiones. La selección del corpus es narrativa y dirigida, no una revisión sistemática exhaustiva ni un metaanálisis.',''])
    (ROOT/'entregables/Referencias_APA.md').write_text('\n'.join(bib),encoding='utf-8')
    for name in ['Contenido_diapositivas.md','Notas_del_ponente_es.md','Referencias_APA.md']:
        path=ROOT/'entregables'/name
        path.write_text('\n'.join(line.rstrip() for line in path.read_text(encoding='utf-8').splitlines())+'\n',encoding='utf-8')
    print(f'Written: {len(notes)} slides; {sum(n["seconds"] for n in notes)} seconds; {sum(len(n["oral"].split()) for n in notes)} spoken words')

if __name__=='__main__': main()
