"""Produce the review matrix and immutable-source inventory for EMAVI."""
from pathlib import Path
import hashlib
import json
import re
import subprocess
import shutil
from preparar_ampliacion import ROOT, VAULT, REFS, SLIDES

# Each entry is a source-specific extraction and appraisal, not a quality score.
REVIEWS = [
('A Multi-Attribute',4,'Artículo de desarrollo','Arquitectura, plugins, scripting; conclusión','OpenMATB facilita personalización, extensión y replicabilidad mediante código y escenarios auditables. Propone ampliar interfaces fisiológicas.','No es un ensayo de validez ni demuestra equivalencia entre configuraciones. La automatización y extensiones citadas corresponden a la versión descrita.'),
('Detecting and Predicting',11,'Revisión sistemática','Resumen; §§4–5; 29 estudios','La HRV puede aportar información sobre carga del piloto, pero los resultados entre métricas y niveles de carga son inconsistentes. Se propone estandarizar diseños y validar en vuelo real.','Heterogeneidad de protocolos y modelos. No proporciona un umbral universal de carga ni permite inferir aptitud individual.'),
('Evaluating input device',13,'Dos experimentos de laboratorio','§§2–5; Exp. 1 y Exp. 2','Exp. 1: 36 reclutados y 35 analizados. Exp. 2: 53 reclutados, con práctica de varios días. El control tipo gamepad presentó ventajas de seguimiento y, tras práctica, de usabilidad/carga en las condiciones examinadas.','Participantes universitarios; familiaridad, mapeo de ejes y práctica son relevantes. No demuestra superioridad para todo vehículo o control real.'),
('Evaluating mental workload',10,'Experimento multimodal','§§2.1–2.2, 3 y resumen; n=26','Universitarios varones realizaron tareas de seguimiento, instrumentos, emergencias y capacidad residual. Mayor demanda se acompañó de mayor NASA-TLX, FC y activación prefrontal.','Paradigma de vuelo multitarea distinto de las cuatro tareas del MATB canónico. Se usa como evidencia convergente de medición multimodal, no como validación directa de MATB.'),
('Feedback on',23,'Ponencia experimental','Participantes; diseño; discusión, interpretación de efectos','28 participantes: 15 deportistas expertos en tareas con presión temporal y 13 novatos. La precalibración con cinco personas no eliminó diferencias de carga percibida entre condiciones.','Grupos con edades distintas y tarea distinta según condición. Ilustra confusión entre naturaleza de tarea y dificultad; no es evidencia en aviadores ni calibración universal.'),
('matb pending',None,'Enlace bibliográfico','Documento completo','Enlace a Recent Developments (2025). El texto de esa publicación existe por separado en el corpus.','No contar como estudio adicional. Duplicado de localización; no aporta resultados.'),
('Multi Attribute Task Battery for Military',None,'Síntesis secundaria sin método reproducible','Resumen ejecutivo y secciones militares','Útil como mapa inicial de nombres e instituciones. Contiene afirmaciones amplias sobre selección, certificación y validez que requieren comprobación en originales.','No usar sus cifras o afirmaciones institucionales como evidencia. Excluida como respaldo primario.'),
('Pilot testing',14,'Estudio piloto','Métodos, resultados y discusión; n=10','Diez estudiantes de medicina realizaron cuatro variantes de MFMG. NASA-TLX fue mayor en A (74,33 ± 14,13) que en C (61,21 ± 16,09); los autores no hallaron diferencias significativas en STAI entre condiciones.','Muestra pequeña y adaptación que incluye preguntas médicas. Carga percibida, ansiedad y fisiología no se intercambian. No demuestra eficacia de un programa clínico de biofeedback.'),
('Quantitative modeling',22,'Experimento en dos fases','§§3.1, 4 y 5; n=25','25 universitarios. Modelo de demanda basado en información y reorganización de pesos de tareas; mejoró el desempeño en la segunda fase dentro del estudio.','Diseño y práctica condicionan la interpretación. No aporta predicción validada de aptitud de vuelo ni normas de selección.'),
('Summarization of',None,'Síntesis secundaria sin verificación','Documento completo','Incluye correlaciones atribuidas a usos militares y selección. Las afirmaciones no se trasladan a diapositivas sin localizar el estudio original y su resultado.','No se verificó el supuesto respaldo de Caldwell et al. para r=0,41–0,57. Se excluyen esas cifras y la afirmación de adopción operacional.'),
('The NASA MATB',9,'Estudio asociativo en simulador','Métodos p.68; resultados y tabla 4 pp.70–71; discusión p.71','51 pilotos licenciados o con permiso y experiencia reciente. Monitoreo, seguimiento y recursos se relacionaron con memoria prospectiva durante vuelo VFR simulado.','Resumen: r²=0,41; texto de resultados: 0,38 y 0,31, con diferencias de modelos y grados de libertad. No reconciliables de forma segura desde la transcripción; no se presenta un porcentaje único. Sin validación externa. Cabecera dice Herdman; ficha bibliográfica contiene Herman.'),
('The United States Army Aeromedical Research Laboratory Multi-Attribute Task Battery-',6,'Actualización técnica breve','§§II–VI; IEEE RAPID 2025','Versión 2.5: modelado IMPRINT, diseño por carga teórica, ajustes VOGL, entrenamiento automatizado de siete minutos y escalas integradas. La métrica compuesta se describe como sujeta a validación adicional.','La copia incluye un residuo editorial de conversión entre páginas. Se corroboraron identidad/DOI; el reporte oficial posterior confirma IMPRINT y las 192 combinaciones. No tratar carga modelada como carga observada ni el índice como validación externa.'),
('The United States Army Aeromedical Research Laboratory Multi-Attribute Task Battery.md',5,'Artículo de desarrollo','§§2.2–2.7; §3; tabla comparativa','Cuatro tareas, transiciones de demanda, automatización adaptable/adaptativa y sincronización con LSL. Describe aplicaciones para carga, confianza y control compartido.','Los ejemplos del artículo no son por sí mismos un ensayo de eficacia ni validación de selección. Conservar versión y reglas de automatización.'),
('THE USAF',3,'Informe técnico AFRL','Introducción p.1; subtareas; scripts; registro y análisis','AF_MATB conserva tareas de la batería y añade herramientas de configuración, creación de scripts y análisis. Ventanas de programación y bombas apoyan estrategias. Informe de julio de 2010, 152 páginas.','Manual de plataforma y uso; no ensayo de validez, norma de certificación ni prueba de adopción en selección de personal.'),
('Three-dimensional',12,'Experimento 2D/VR','Métodos; resultados; §§4–5; n=49','53 reclutados; cuatro excluidos por malestar en VR, 49 analizados. Separación de tareas en profundidad se acompañó de peor desempeño, mayor NASA-TLX y menor RMSSD que la condición sin profundidad.','Tareas de seguimiento y monitoreo y configuración de profundidad específica. No generalizar a toda VR, a simulación multiaxial ni a pilotos. Año del fascículo 2025; DOI contiene 2024.'),
('Transcranial',24,'Ensayo en simulador de helicóptero','Métodos; resultados; discusión','Ensayo aleatorizado, ciego simple y con sham en simulador Black Hawk. Evalúa momento de estimulación y métricas de trayectoria durante una emergencia.','Evidencia indirecta de investigación aeronáutica multimodal. No es una validación de MATB ni una intervención propuesta para ASTRA. No extrapolar beneficios o seguridad a la misión.'),
]

NASA = [
('Behavioral Med._Schedule.pdf',None,'Mapa de investigación BMed','Documento completo','Organiza caracterización, contramedidas e integración/validación. Se utiliza como lógica de desarrollo gradual.','Cronograma de investigación, no estudio empírico ni prueba de que las contramedidas ya funcionan.'),
('HRP-ER-BMED-HFBP-20250210.pdf',16,'Informe de evidencia NASA','Declaración de riesgo y resumen ejecutivo; secciones de análogos','Marco para estudiar cambios cognitivos y conductuales bajo exposición combinada a peligros espaciales.','ASTRA representa aislamiento y confinamiento terrestres; no reproduce radiación ni gravedad alterada.'),
('OP Dynamic Loads EB FINAL_11-30-22.pdf',20,'Informe de evidencia NASA','Resumen ejecutivo, pp.12–14; mecanismos y criterios','Describe riesgo de lesión por cargas transitorias, aceleración/desaceleración, lanzamiento y aterrizaje.','Delimita lo que requiere ensayos físicos o simulación biomecánica. No fundamenta validez cognitiva de MATB.'),
('Risk of Inadequate HSIA approved FINAL_ 6-13-2023.pdf',19,'Informe de evidencia NASA','Declaración de riesgo; contexto y arquitectura HSIA','Integra hábitat, interacción persona-computador, automatización/robótica, entrenamiento y diseño de tareas.','Portada: aprobación pública 15-04-2021; nombre de archivo: 2023. No asumir que el nombre demuestra una nueva edición aprobada.'),
('Sleep.pdf',17,'Informe de evidencia NASA','Resumen ejecutivo; sueño, circadianidad y sobrecarga','Fundamenta registrar sueño y carga como contexto de desempeño. Portada: 11-04-2016.','Fuente histórica; no se presenta como la edición más reciente ni prueba de sueño realmente observado en ASTRA.'),
('Team 2022 -Evidence Report FINAL_5-9-2024.pdf',18,'Informe de evidencia NASA','Declaración de riesgo; resumen ejecutivo; evidencia en análogos','Apoya estudiar cooperación, coordinación, comunicación y adaptación psicosocial. Destaca el papel de análogos terrestres.','Portada: 10-06-2022; archivo con sufijo 2024. Riesgo y magnitud de misiones espaciales no se transfieren directamente a ASTRA.'),
]

def main():
    records=[]
    literature=VAULT/'Experimentos/Open MATB/Research'
    for prefix,ref,kind,locator,finding,limit in REVIEWS:
        candidates=list(literature.glob(prefix if prefix.endswith('.md') else prefix+'*.md'))
        assert len(candidates)==1,(prefix,candidates)
        p=candidates[0]
        # Read the entire available text; preserve original files without copying them.
        text=p.read_text(encoding='utf-8-sig')
        records.append({'id':'MATB-'+str(len(records)+1).zfill(2),'reference':ref,'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'lines':len(text.splitlines()),'kind':kind,'locator':locator,'finding':finding,'limitations':limit,'reviewed_on':'2026-09-27'})
    for name,ref,kind,locator,finding,limit in NASA:
        p=VAULT/'Research'/name
        txt=subprocess.run([shutil.which('pdftotext'),'-layout',str(p),'-'],capture_output=True,check=True).stdout.decode('utf-8','replace')
        records.append({'id':'NASA-'+str(sum(x['id'].startswith('NASA') for x in records)+1).zfill(2),'reference':ref,'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'extracted_characters':len(txt),'pages':len(txt.split('\f'))-1,'kind':kind,'locator':locator,'finding':finding,'limitations':limit,'reviewed_on':'2026-09-27'})
    for name in ['Manual de Operaciones ASTRA 2026.md','Cronograma consolidado de tripulaciones ASTRA 1 y 2 - 2026.md','Protocolo de línea de base única ASTRA 2026.md','Plan de adquisición y rotación ActiGraph Polar H10 ASTRA 2026.md','Conciliación del cronograma y autonomía de sensores ASTRA 2026.md','Programa de evaluaciones y briefings premision ASTRA 2026.md','Habitat Safety Checklist.md','Verificación de referencias - Manual ASTRA 2026.md']:
        p=VAULT/'Manual de Operaciones'/name
        records.append({'id':'OPS-'+str(sum(x['id'].startswith('OPS') for x in records)+1).zfill(2),'reference':21,'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'kind':'Documento operativo local','locator':'Manual: §§1–4, calendario vigente, §4.7; documentos complementarios según su objeto','finding':'Planificación y procedimientos; fechas, recursos y actividades se presentan como previstos.','limitations':'No acredita aprobación final, disponibilidad, ejecución ni resultados humanos.','reviewed_on':'2026-09-27'})
    for ref,locator,finding,limit in [
        (1,'NTRS: resumen y registro 19920007912','Benchmark de tareas semejantes a actividades de tripulación, con control experimental y participantes no pilotos.','Propósito de plataforma; no validación selectiva.'),
        (2,'NASA/TM-2011-217164: guía y configuración','Implementación MATB-II y registro por tareas.','Manual técnico, no estudio psicométrico.'),
        (7,'Informe 26-11-2025: Summary p.iii; métodos pp.8–15; tabla 3 p.19; limitaciones pp.42–43','24 aviadores; diseño intraindividual 2 × 2. Efecto multivariado comunicado de transparencia sobre carga: p=0,002; η²=0,35. Control voluntario favoreció confianza.','Reporte técnico, muestra pequeña, contrastes categóricos, entorno de escritorio y corta exposición. Se conserva η² como lo rotula el informe; no se relabela como η² parcial. No se usan exactitudes de clasificación como validez de selección.'),
        (8,'Resumen y sección de configuración; revisión de 19 estudios','Mayor demanda puede elevar carga y reducir desempeño; siete estudios describieron configuración con suficiente detalle.','Síntesis heterogénea; no usar medianas de eventos como umbrales universales.'),
        (15,'NTRS 20220017200; sección de HATTB en manuscrito SciTech 2023','La filosofía de HATTB se inspira en MATB para estudiar coordinación humano-autonomía y operaciones UAS de múltiples vehículos.','HATTB es otro banco experimental; no es funcionalidad de NASA MATB-II ni un despliegue operativo certificado.')]:
        records.append({'id':f'WEB-{ref:02}','reference':ref,'url':REFS[ref][2],'kind':'Fuente primaria o revisión publicada complementaria','locator':locator,'finding':finding,'limitations':limit,'reviewed_on':'2026-09-27','discovery':'Tavily MCP; Undermind corroboró referencias 5, 6, 8 y 9 durante planificación.'})
    (ROOT/'fuentes/registro_fuentes.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    out=['# Revisión crítica y matriz de evidencia · EMAVI','','Revisión narrativa estructurada del corpus solicitado. Fecha: 27-09-2026. No es una búsqueda sistemática exhaustiva ni un metaanálisis. Se revisaron los 16 documentos MATB, los seis PDF NASA y ocho documentos operativos; las versiones históricas no sustituyen el manual v2.6. Los DOCX paralelos no se cuentan como estudios adicionales. Los originales permanecen en su ubicación, sin modificación ni redistribución.','', '## Síntesis científica','','La evidencia más directa respalda investigación de demanda, estrategias y automatización bajo condiciones definidas. La sensibilidad a la demanda no equivale a fiabilidad entre sesiones, y una asociación con un simulador no establece validez externa ni utilidad para selección. La comparación entre plataformas debe preservar versión, dispositivos, parámetros y entrenamiento.','','El informe oficial de USAARL aporta un ejemplo reciente con 24 aviadores; sus resultados dependen de las manipulaciones de transparencia y transferencia. La literatura de OpenMATB y AF_MATB aporta arquitectura y procedimientos, no certificación psicométrica. La evidencia con memoria prospectiva es prometedora pero asociativa. La VR y los dispositivos de entrada muestran que una interfaz más compleja puede modificar la tarea que se pretende medir.','','La revisión de HRV y el experimento de Li apoyan medición multimodal con condiciones y límites explícitos. Li empleó un paradigma distinto del MATB canónico; Feltman y Kelley emplearon un simulador Black Hawk. Ninguno se contabiliza como validación directa del MATB. La adaptación médica separa carga subjetiva de ansiedad; no autoriza una equivalencia automática entre estrés, carga y fisiología.','','En ASTRA se prioriza el manual v2.6: dos ciclos de 15 días, meta nominal de seis por misión, ocho visitas MATB y medición por dominios. Las fechas son previstas. La contingencia de siete/ocho personas en ASTRA 2 no se presenta como cambio confirmado de la muestra nominal. El análogo es terrestre a presión ambiental local; no reproduce fuerzas multiaxiales, vacío, gravedad lunar ni radiación espacial.','','## Matriz por documento','']
    for x in records:
        out.extend([f'### {x["id"]} · '+(Path(x['path']).name if 'path'in x else REFS[x['reference']][0]),'',f'**Tipo:** {x["kind"]}. **Localizador:** {x["locator"]}.', '', '**Extracción:** '+x['finding'],'','**Límites y decisión editorial:** '+x['limitations'],''])
        if x['reference']:out.append('**Diapositivas:** '+', '.join(str(s['n']) for s in SLIDES if x['reference'] in s['refs'])+'.\n')
    out.extend(['## Discrepancias resueltas para la presentación','','- No se trasladan las afirmaciones generales sobre selección y certificación de las dos notas de síntesis militar.\n- No se publica un R² único del trabajo de memoria prospectiva; las cifras de resumen y resultados no coinciden.\n- El informe USAARL con identificador 2026-02 está fechado el 26 de noviembre de 2025.\n- Los nombres de los PDF Team y HSIA no sustituyen las fechas de sus portadas.\n- Manual ASTRA: V0–V7, con DM7 como visita MATB intermedia. Software astra-2026: T0/DM8/DM15. La diferencia permanece documentada, sin modificar el protocolo ni la base.\n- Las capturas siguen siendo documentales y sintéticas; no representan validación humana.\n- Se preserva la corrección manual observada en el PowerPoint original, sin reinsertar los dos puntos CEINNA/EMAVI retirados de su antigua diapositiva 19.','', '## Afirmaciones por diapositiva',''] )
    claims=[]
    for s in SLIDES:
        c=s['content']; text=c.get('body') or '\n'.join(c.get('bullets',[])) or '\n'.join(' | '.join(row) for row in c['rows'])
        claims.append({'slide':s['n'],'title':c['title'],'visible_content':text,'references':s['refs'],'source_records':[r['id'] for r in records if r['reference'] in s['refs'] and r['reference'] is not None],'status':'source_checked','scope':'Demostración técnica sintética' if 24<=s['n']<=30 else 'Plan previsto' if 16<=s['n']<=23 else 'Síntesis o propuesta de investigación; ver notas'})
        out.extend([f'- **{s["n"]}. {c["title"]}:** '+(', '.join(f'[{r}]' for r in s['refs']) or 'Procedencia de capturas e informes técnicos locales')+'.'])
    (ROOT/'entregables/Revision_evidencia_MATB_ASTRA.md').write_text('\n'.join(out)+'\n',encoding='utf-8')
    (ROOT/'fuentes/matriz_afirmaciones.json').write_text(json.dumps(claims,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(f'{len(records)} source records; 16 MATB documents; 6 NASA PDFs; {len(claims)} slide mappings')

if __name__=='__main__': main()
