import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { missionFixture } from "./mission-fixture.js";
for (const fixture of [{ name: "desktop", width: 1440, height: 1000 }, { name: "tablet", width: 820, height: 1180 }] as const) {
  test(`has no serious or critical axe violations in authenticated ${fixture.name}`, async ({ page }) => {
    const missionId = `mission-a11y-${fixture.name}`; await page.setViewportSize({ width: fixture.width, height: fixture.height }); await page.goto("/"); await page.getByLabel("User ID").fill("commander-1"); await page.getByLabel("Password").fill("correct horse battery staple"); await page.getByRole("button", { name: "Sign in", exact: true }).click(); await expect(page.getByRole("heading", { name: "Missions" })).toBeVisible();
    await page.getByText("Create mission", { exact: true }).first().click(); await page.getByLabel("Mission JSON").fill(JSON.stringify(missionFixture(missionId))); await page.getByRole("button", { name: "Create mission" }).click(); await expect(page.getByText(missionId, { exact: true })).toBeVisible(); await page.getByRole("button").filter({ hasText: missionId }).click();
    await page.getByLabel("Re-authentication password").fill("correct horse battery staple"); await page.getByRole("button", { name: "Re-authenticate" }).click(); await expect(page.getByLabel("Re-authentication password")).toHaveValue(""); await page.getByLabel("Item ID").fill(`${fixture.name}-a11y-check`); await page.getByLabel("Reason", { exact: true }).first().fill("axe populated-state evidence"); await page.getByRole("button", { name: "Respond to item" }).click(); await expect(page.getByText(`${fixture.name}-a11y-check`, { exact: true })).toBeVisible();
    const commander = page.locator(".gate-live").filter({ has: page.getByRole("heading", { name: "commander", exact: true }) }); await commander.getByLabel("Decision").selectOption("block"); await commander.getByLabel("Reason").fill("representative populated blocked gate"); await commander.getByRole("button", { name: "Record gate" }).click(); await expect(commander.getByRole("status").first()).toHaveText("Block");
    if (fixture.name === "tablet") { await page.getByRole("button", { name: "Change language" }).click(); await expect(page.getByRole("heading", { name: "Misiones" })).toBeVisible(); } const results = await new AxeBuilder({ page }).analyze(); expect(results.violations.filter(({ impact }) => impact === "critical" || impact === "serious"), JSON.stringify(results.violations, null, 2)).toEqual([]);
  });
}
